"""phase1 baseline

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

# UTC timestamps: DATETIME2(6) on SQL Server (DATETIME rounds to 1/300 s and would break audit hashes)
UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")

_AO_0001 = ("audit_trail", "e_signature", "security_event", "gmp_status_history", "record_action", "workflow_transaction")

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_head',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('lock_counter', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_chain_head'))
    )
    op.create_table('audit_trail',
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('tz_name', sa.String(length=60), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_name', sa.String(length=150), nullable=False),
    sa.Column('role_name', sa.String(length=300), nullable=True),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_info', sa.String(length=300), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_trail'))
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity_record', ['entity', 'record_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_time', ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_user_time', ['user_id', 'occurred_at'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('original_name', sa.String(length=260), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('uploaded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('uploaded_at', UTC_DT, nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['document.id'], name=op.f('fk_document_supersedes_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sha256'), ['sha256'], unique=False)

    op.create_table('error_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('route', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_log'))
    )
    op.create_table('gmp_status_history',
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('from_status', sa.String(length=40), nullable=True),
    sa.Column('to_status', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmp_status_history'))
    )
    with op.batch_alter_table('gmp_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_status_hist_record', ['entity', 'record_id'], unique=False)

    op.create_table('permission',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('perm_code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('resource', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('perm_code', name=op.f('uq_permission_perm_code'))
    )
    op.create_table('record_action',
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record_action'))
    )
    with op.batch_alter_table('record_action', schema=None) as batch_op:
        batch_op.create_index('ix_record_action', ['entity', 'record_id', 'action_code'], unique=False)

    op.create_table('role',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_admin_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('role_code', name=op.f('uq_role_role_code'))
    )
    op.create_table('security_event',
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_event'))
    )
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_event_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('sod_rule',
    sa.Column('sod_id', sa.String(length=20), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('conflicts_with_action_code', sa.String(length=100), nullable=False),
    sa.Column('enforcement', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("enforcement IN ('BLOCK','WARN')", name=op.f('ck_sod_rule_enforcement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sod_rule')),
    sa.UniqueConstraint('action_code', 'conflicts_with_action_code', name=op.f('uq_sod_rule_action_code'))
    )
    op.create_table('system_configuration',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configuration')),
    sa.UniqueConstraint('config_key', name=op.f('uq_system_configuration_config_key'))
    )
    op.create_table('company',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('app_display_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('manufacturing_licence_no', sa.String(length=60), nullable=True),
    sa.Column('drug_licence_no', sa.String(length=60), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=150), nullable=True),
    sa.Column('logo_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('document_header', sa.Text(), nullable=True),
    sa.Column('document_footer', sa.Text(), nullable=True),
    sa.Column('report_format', sa.String(length=50), nullable=True),
    sa.Column('label_format', sa.String(length=50), nullable=True),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('time_format', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logo_document_id'], ['document.id'], name=op.f('fk_company_logo_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company'))
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('permission_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revoked_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name=op.f('fk_role_permission_permission_id_permission')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_role_permission_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permission')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permission_role_id'))
    )
    op.create_table('plant',
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plant_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_plant_company_id_company')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plant')),
    sa.UniqueConstraint('plant_code', name=op.f('uq_plant_plant_code'))
    )
    op.create_table('department',
    sa.Column('plant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name=op.f('fk_department_plant_id_plant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('plant_id', 'code', name=op.f('uq_department_plant_id'))
    )
    op.create_table('number_registry',
    sa.Column('plant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('reset_policy', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("reset_policy IN ('YEARLY','NEVER')", name=op.f('ck_number_registry_reset_policy')),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name=op.f('fk_number_registry_plant_id_plant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_registry')),
    sa.UniqueConstraint('plant_id', 'doc_type', name=op.f('uq_number_registry_plant_id'))
    )
    op.create_table('number_sequence',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('current_value', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name=op.f('fk_number_sequence_plant_id_plant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_sequence')),
    sa.UniqueConstraint('plant_id', 'doc_type', 'period_key', name=op.f('uq_number_sequence_plant_id'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('plant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('auth_source', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('password_changed_at', UTC_DT, nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_expiry', sa.Date(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', UTC_DT, nullable=True),
    sa.Column('last_login_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("auth_source IN ('LOCAL','LDAP')", name=op.f('ck_users_auth_source')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_users_department_id_department')),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name=op.f('fk_users_plant_id_plant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('e_signature',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('signed_at', UTC_DT, nullable=False),
    sa.Column('tz_name', sa.String(length=60), nullable=False),
    sa.Column('printed_name', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('role_name', sa.String(length=300), nullable=True),
    sa.Column('meaning', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('record_version', sa.String(length=30), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_e_signature_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_e_signature'))
    )
    with op.batch_alter_table('e_signature', schema=None) as batch_op:
        batch_op.create_index('ix_esig_record', ['entity', 'record_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ref_entity', sa.String(length=80), nullable=True),
    sa.Column('ref_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('read_at', UTC_DT, nullable=True),
    sa.Column('emailed_at', UTC_DT, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user', ['user_id', 'read_at'], unique=False)

    op.create_table('password_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('set_at', UTC_DT, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_history'))
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_history_user_id'), ['user_id'], unique=False)

    op.create_table('training_record',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('training_code', sa.String(length=60), nullable=False),
    sa.Column('document_version', sa.String(length=20), nullable=True),
    sa.Column('trained_on', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_record_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_record'))
    )
    with op.batch_alter_table('training_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_record_user_id'), ['user_id'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('granted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', UTC_DT, nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_user_role_granted_by_id_users')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_role_id_role')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', 'valid_from', name=op.f('uq_user_role_user_id'))
    )
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_index('ix_user_role_user', ['user_id'], unique=False)

    op.create_table('user_session',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('last_seen_at', UTC_DT, nullable=False),
    sa.Column('absolute_expires_at', UTC_DT, nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('revoked_at', UTC_DT, nullable=True),
    sa.Column('revoke_reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_session_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index('ix_user_session_user', ['user_id'], unique=False)

    op.create_table('workflow_definition',
    sa.Column('process_code', sa.String(length=60), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','APPROVED','SUPERSEDED')", name=op.f('ck_workflow_definition_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_workflow_definition_approved_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition')),
    sa.UniqueConstraint('process_code', 'version_no', name=op.f('uq_workflow_definition_process_code'))
    )
    op.create_table('workflow_instance',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('process_code', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_seq', sa.Integer(), nullable=False),
    sa.Column('initiated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', UTC_DT, nullable=False),
    sa.Column('step_started_at', UTC_DT, nullable=False),
    sa.Column('completed_at', UTC_DT, nullable=True),
    sa.CheckConstraint("status IN ('IN_PROGRESS','APPROVED','REJECTED','CANCELLED')", name=op.f('ck_workflow_instance_status')),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_instance_definition_id_workflow_definition')),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], name=op.f('fk_workflow_instance_initiated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instance'))
    )
    with op.batch_alter_table('workflow_instance', schema=None) as batch_op:
        batch_op.create_index('ix_wfi_record', ['entity', 'record_id'], unique=False)

    op.create_table('workflow_step',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('min_approvals', sa.Integer(), nullable=False),
    sa.Column('esig_required', sa.Boolean(), nullable=False),
    sa.Column('meaning', sa.String(length=40), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('escalate_role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reject_to_seq', sa.Integer(), nullable=True),
    sa.CheckConstraint('min_approvals >= 1', name=op.f('ck_workflow_step_min_approvals')),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_step_definition_id_workflow_definition')),
    sa.ForeignKeyConstraint(['escalate_role_id'], ['role.id'], name=op.f('fk_workflow_step_escalate_role_id_role')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_workflow_step_role_id_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step')),
    sa.UniqueConstraint('definition_id', 'seq', name=op.f('uq_workflow_step_definition_id'))
    )
    op.create_table('workflow_transaction',
    sa.Column('instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_workflow_transaction_actor_id_users')),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], name=op.f('fk_workflow_transaction_instance_id_workflow_instance')),
    sa.ForeignKeyConstraint(['signature_id'], ['e_signature.id'], name=op.f('fk_workflow_transaction_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transaction'))
    )
    with op.batch_alter_table('workflow_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_transaction_instance_id'), ['instance_id'], unique=False)

    # ### end Alembic commands ###

    # Immutability triggers for append-only GMP tables (dialect specific; see app/audit/immutability.py)
    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0001)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0001)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_transaction_instance_id'))

    op.drop_table('workflow_transaction')
    op.drop_table('workflow_step')
    with op.batch_alter_table('workflow_instance', schema=None) as batch_op:
        batch_op.drop_index('ix_wfi_record')

    op.drop_table('workflow_instance')
    op.drop_table('workflow_definition')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index('ix_user_session_user')

    op.drop_table('user_session')
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role_user')

    op.drop_table('user_role')
    with op.batch_alter_table('training_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_record_user_id'))

    op.drop_table('training_record')
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_history_user_id'))

    op.drop_table('password_history')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user')

    op.drop_table('notification')
    with op.batch_alter_table('e_signature', schema=None) as batch_op:
        batch_op.drop_index('ix_esig_record')

    op.drop_table('e_signature')
    op.drop_table('users')
    op.drop_table('number_sequence')
    op.drop_table('number_registry')
    op.drop_table('department')
    op.drop_table('plant')
    op.drop_table('role_permission')
    op.drop_table('company')
    op.drop_table('system_configuration')
    op.drop_table('sod_rule')
    with op.batch_alter_table('security_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_event_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_security_event_event_type'))

    op.drop_table('security_event')
    op.drop_table('role')
    with op.batch_alter_table('record_action', schema=None) as batch_op:
        batch_op.drop_index('ix_record_action')

    op.drop_table('record_action')
    op.drop_table('permission')
    with op.batch_alter_table('gmp_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_status_hist_record')

    op.drop_table('gmp_status_history')
    op.drop_table('error_log')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sha256'))

    op.drop_table('document')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_time')
        batch_op.drop_index('ix_audit_time')
        batch_op.drop_index('ix_audit_entity_record')

    op.drop_table('audit_trail')
    op.drop_table('audit_chain_head')
    # ### end Alembic commands ###
