"""phase2 master data

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

# UTC timestamps: DATETIME2(6) on SQL Server (DATETIME rounds to 1/300 s and would break audit hashes)
UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('code', name=op.f('uq_category_code'))
    )
    op.create_table('customer',
    sa.Column('customer_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('licence_no', sa.String(length=60), nullable=True),
    sa.Column('licence_expiry', sa.Date(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_authorised', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('customer_code', name=op.f('uq_customer_customer_code'))
    )
    op.create_table('material_type',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_stock_item', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_type')),
    sa.UniqueConstraint('code', name=op.f('uq_material_type_code'))
    )
    op.create_table('unit',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit')),
    sa.UniqueConstraint('code', name=op.f('uq_unit_code'))
    )
    op.create_table('vendor',
    sa.Column('vendor_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vendor_type', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('pan_no', sa.String(length=15), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=40), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('material_categories', sa.String(length=300), nullable=True),
    sa.Column('risk_class', sa.String(length=10), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('quality_agreement_status', sa.String(length=20), nullable=False),
    sa.Column('vendor_audit_status', sa.String(length=20), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("approval_status IN ('DRAFT','APPROVED','INACTIVE')", name=op.f('ck_vendor_approval_status')),
    sa.CheckConstraint("risk_class IN ('CRITICAL','HIGH','MEDIUM','LOW')", name=op.f('ck_vendor_risk_class')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor')),
    sa.UniqueConstraint('vendor_code', name=op.f('uq_vendor_vendor_code'))
    )
    op.create_table('doc_link',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('linked_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('linked_at', UTC_DT, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_doc_link_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_link')),
    sa.UniqueConstraint('document_id', 'entity', 'record_id', name=op.f('uq_doc_link_document_id'))
    )
    with op.batch_alter_table('doc_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doc_link_entity'), ['entity'], unique=False)

    op.create_table('import_job',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('submitted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('imported_at', UTC_DT, nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('UPLOADED','VALIDATED','REJECTED','SUBMITTED','APPROVED','IMPORTED','FAILED')", name=op.f('ck_import_job_status')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_import_job_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_job'))
    )
    op.create_table('location_compat_rule',
    sa.Column('category_a_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_b_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_a_id'], ['category.id'], name=op.f('fk_location_compat_rule_category_a_id_category')),
    sa.ForeignKeyConstraint(['category_b_id'], ['category.id'], name=op.f('fk_location_compat_rule_category_b_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_compat_rule')),
    sa.UniqueConstraint('category_a_id', 'category_b_id', name=op.f('uq_location_compat_rule_category_a_id'))
    )
    op.create_table('material',
    sa.Column('material_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('type_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('pharmacopoeial_standard', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('base_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=True),
    sa.Column('storage_condition', sa.String(length=200), nullable=True),
    sa.Column('temp_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temp_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('retest_days', sa.Integer(), nullable=True),
    sa.Column('requires_qc', sa.Boolean(), nullable=False),
    sa.Column('requires_qa_release', sa.Boolean(), nullable=False),
    sa.Column('gmp_criticality', sa.String(length=20), nullable=False),
    sa.Column('hazard_class', sa.String(length=60), nullable=True),
    sa.Column('fefo_mode', sa.String(length=4), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_stock', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('master_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("fefo_mode IN ('FEFO','FIFO')", name=op.f('ck_material_fefo_mode')),
    sa.CheckConstraint("master_status IN ('DRAFT','APPROVED','ACTIVE','OBSOLETE')", name=op.f('ck_material_master_status')),
    sa.CheckConstraint('shelf_life_days IS NULL OR shelf_life_days > 0', name=op.f('ck_material_shelf_life')),
    sa.CheckConstraint('temp_max IS NULL OR temp_min IS NULL OR temp_max >= temp_min', name=op.f('ck_material_temp_range')),
    sa.ForeignKeyConstraint(['base_unit_id'], ['unit.id'], name=op.f('fk_material_base_unit_id_unit')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_material_category_id_category')),
    sa.ForeignKeyConstraint(['type_id'], ['material_type.id'], name=op.f('fk_material_type_id_material_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material')),
    sa.UniqueConstraint('material_code', name=op.f('uq_material_material_code'))
    )
    op.create_table('unit_conversion',
    sa.Column('from_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('to_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('factor', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('factor > 0', name=op.f('ck_unit_conversion_factor_positive')),
    sa.ForeignKeyConstraint(['from_unit_id'], ['unit.id'], name=op.f('fk_unit_conversion_from_unit_id_unit')),
    sa.ForeignKeyConstraint(['to_unit_id'], ['unit.id'], name=op.f('fk_unit_conversion_to_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_conversion')),
    sa.UniqueConstraint('from_unit_id', 'to_unit_id', name=op.f('uq_unit_conversion_from_unit_id'))
    )
    op.create_table('vendor_document',
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('doc_no', sa.String(length=60), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', UTC_DT, nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("review_status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_vendor_document_review_status')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_vendor_document_document_id_document')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_vendor_document_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_document'))
    )
    with op.batch_alter_table('vendor_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_document_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('import_row',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['import_job.id'], name=op.f('fk_import_row_job_id_import_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row'))
    )
    with op.batch_alter_table('import_row', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_row_job_id'), ['job_id'], unique=False)

    op.create_table('warehouse',
    sa.Column('plant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('storage_condition', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], name=op.f('fk_warehouse_plant_id_plant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse')),
    sa.UniqueConstraint('warehouse_code', name=op.f('uq_warehouse_warehouse_code'))
    )
    op.create_table('location',
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('location_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=10), nullable=False),
    sa.Column('storage_condition', sa.String(length=100), nullable=True),
    sa.Column('temp_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temp_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('capacity_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('current_occupancy', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_quarantine', sa.Boolean(), nullable=False),
    sa.Column('is_rejected_area', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("location_type IN ('ZONE','ROOM','RACK','SHELF','BIN')", name=op.f('ck_location_location_type')),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name=op.f('ck_location_capacity')),
    sa.CheckConstraint('temp_max IS NULL OR temp_min IS NULL OR temp_max >= temp_min', name=op.f('ck_location_temp_range')),
    sa.ForeignKeyConstraint(['capacity_unit_id'], ['unit.id'], name=op.f('fk_location_capacity_unit_id_unit')),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], name=op.f('fk_location_parent_id_location')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_location_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location')),
    sa.UniqueConstraint('location_code', name=op.f('uq_location_location_code'))
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('equipment',
    sa.Column('equipment_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('equipment_type', sa.String(length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_no', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('qualification_status', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calibration_required', sa.Boolean(), nullable=False),
    sa.Column('calibration_due', sa.Date(), nullable=True),
    sa.Column('maintenance_due', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("qualification_status IN ('NOT_QUALIFIED','QUALIFIED','REQUALIFICATION_DUE','DISQUALIFIED')", name=op.f('ck_equipment_qualification_status')),
    sa.CheckConstraint("status IN ('ACTIVE','UNDER_MAINTENANCE','OUT_OF_SERVICE','RETIRED')", name=op.f('ck_equipment_status')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_equipment_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('equipment_code', name=op.f('uq_equipment_equipment_code'))
    )
    op.create_table('location_category',
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('revoked_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_location_category_category_id_category')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_location_category_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_category')),
    sa.UniqueConstraint('location_id', 'category_id', name=op.f('uq_location_category_location_id'))
    )
    op.create_table('calibration',
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=4), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('certificate_no', sa.String(length=80), nullable=True),
    sa.Column('certificate_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("result IN ('PASS','FAIL')", name=op.f('ck_calibration_result')),
    sa.CheckConstraint('due_on > performed_on', name=op.f('ck_calibration_due_after_performed')),
    sa.ForeignKeyConstraint(['certificate_document_id'], ['document.id'], name=op.f('fk_calibration_certificate_document_id_document')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_calibration_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calibration'))
    )
    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('sampling_plan',
    sa.Column('plan_no', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sampling_rule', sa.String(length=15), nullable=False),
    sa.Column('fixed_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('percent', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('container_rule', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("sampling_rule IN ('FIXED','SQRT_N_PLUS_1','PERCENT','ALL')", name=op.f('ck_sampling_plan_sampling_rule')),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_sampling_plan_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_sampling_plan_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_sampling_plan_material_id_material')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['sampling_plan.id'], name=op.f('fk_sampling_plan_supersedes_id_sampling_plan')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_sampling_plan_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sampling_plan')),
    sa.UniqueConstraint('plan_no', 'version_no', name=op.f('uq_sampling_plan_plan_no'))
    )
    with op.batch_alter_table('sampling_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sampling_plan_material_id'), ['material_id'], unique=False)

    op.create_table('specification',
    sa.Column('spec_no', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pharmacopoeial_reference', sa.String(length=100), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_specification_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_specification_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_specification_material_id_material')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['specification.id'], name=op.f('fk_specification_supersedes_id_specification')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specification')),
    sa.UniqueConstraint('spec_no', 'version_no', name=op.f('uq_specification_spec_no'))
    )
    with op.batch_alter_table('specification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specification_material_id'), ['material_id'], unique=False)

    op.create_table('stp',
    sa.Column('stp_no', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('test_method', sa.String(length=200), nullable=True),
    sa.Column('equipment_required', sa.Text(), nullable=True),
    sa.Column('reagents_required', sa.Text(), nullable=True),
    sa.Column('reference_standards', sa.Text(), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('calculation', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('safety_precautions', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_stp_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_stp_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['stp.id'], name=op.f('fk_stp_supersedes_id_stp')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stp')),
    sa.UniqueConstraint('stp_no', 'version_no', name=op.f('uq_stp_stp_no'))
    )
    op.create_table('specification_parameter',
    sa.Column('specification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('test_method', sa.String(length=150), nullable=True),
    sa.Column('stp_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('spec_type', sa.String(length=10), nullable=False),
    sa.Column('lsl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('acceptance_criteria', sa.String(length=300), nullable=True),
    sa.Column('pharmacopoeial_reference', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=60), nullable=True),
    sa.Column('criticality', sa.String(length=10), nullable=False),
    sa.Column('alert_low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('alert_high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('action_low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('action_high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("criticality IN ('CRITICAL','MAJOR','MINOR')", name=op.f('ck_specification_parameter_criticality')),
    sa.CheckConstraint("spec_type IN ('NUMERIC','RANGE','TEXT','PASS_FAIL')", name=op.f('ck_specification_parameter_spec_type')),
    sa.CheckConstraint('usl IS NULL OR lsl IS NULL OR usl >= lsl', name=op.f('ck_specification_parameter_usl_ge_lsl')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], name=op.f('fk_specification_parameter_specification_id_specification')),
    sa.ForeignKeyConstraint(['stp_id'], ['stp.id'], name=op.f('fk_specification_parameter_stp_id_stp')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specification_parameter')),
    sa.UniqueConstraint('specification_id', 'seq', name=op.f('uq_specification_parameter_specification_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification_parameter')
    op.drop_table('stp')
    with op.batch_alter_table('specification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specification_material_id'))

    op.drop_table('specification')
    with op.batch_alter_table('sampling_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sampling_plan_material_id'))

    op.drop_table('sampling_plan')
    with op.batch_alter_table('calibration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_equipment_id'))

    op.drop_table('calibration')
    op.drop_table('location_category')
    op.drop_table('equipment')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_warehouse_id'))

    op.drop_table('location')
    op.drop_table('warehouse')
    with op.batch_alter_table('import_row', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_row_job_id'))

    op.drop_table('import_row')
    with op.batch_alter_table('vendor_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_document_vendor_id'))

    op.drop_table('vendor_document')
    op.drop_table('unit_conversion')
    op.drop_table('material')
    op.drop_table('location_compat_rule')
    op.drop_table('import_job')
    with op.batch_alter_table('doc_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doc_link_entity'))

    op.drop_table('doc_link')
    op.drop_table('vendor')
    op.drop_table('unit')
    op.drop_table('material_type')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
