"""phase3 purchase

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_material',
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('manufacturer_site', sa.String(length=200), nullable=True),
    sa.Column('change_control_ref', sa.String(length=60), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('approved_to', sa.Date(), nullable=True),
    sa.Column('status_reason', sa.String(length=1000), nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED','WITHDRAWN')", name=op.f('ck_vendor_material_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_vendor_material_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_vendor_material_material_id_material')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['vendor_material.id'], name=op.f('fk_vendor_material_supersedes_id_vendor_material')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_vendor_material_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_material')),
    sa.UniqueConstraint('vendor_id', 'material_id', 'version_no', name=op.f('uq_vendor_material_vendor_id'))
    )
    with op.batch_alter_table('vendor_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_material_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_material_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_qualification',
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qualification_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_class', sa.String(length=10), nullable=False),
    sa.Column('qualified_on', sa.Date(), nullable=True),
    sa.Column('requalification_due_date', sa.Date(), nullable=True),
    sa.Column('basis', sa.Text(), nullable=True),
    sa.Column('audit_report_ref', sa.String(length=100), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('status_reason', sa.String(length=1000), nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("risk_class IN ('CRITICAL','HIGH','MEDIUM','LOW')", name=op.f('ck_vendor_qualification_risk_class')),
    sa.CheckConstraint("status IN ('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'CONDITIONAL', 'SUSPENDED', 'EXPIRED', 'DISQUALIFIED', 'SUPERSEDED')", name=op.f('ck_vendor_qualification_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_vendor_qualification_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['vendor_qualification.id'], name=op.f('fk_vendor_qualification_supersedes_id_vendor_qualification')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_vendor_qualification_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_qualification')),
    sa.UniqueConstraint('vendor_id', 'version_no', name=op.f('uq_vendor_qualification_vendor_id'))
    )
    with op.batch_alter_table('vendor_qualification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_qualification_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('purchase_request',
    sa.Column('pr_no', sa.String(length=30), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('workflow_instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('LOW','NORMAL','HIGH','URGENT')", name=op.f('ck_purchase_request_priority')),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','DEPARTMENT_APPROVED','APPROVED','CONVERTED','REJECTED','CANCELLED')", name=op.f('ck_purchase_request_status')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_purchase_request_department_id_department')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_purchase_request_requested_by_id_users')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], name=op.f('fk_purchase_request_workflow_instance_id_workflow_instance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_request')),
    sa.UniqueConstraint('pr_no', name=op.f('uq_purchase_request_pr_no'))
    )
    op.create_table('purchase_order',
    sa.Column('po_no', sa.String(length=30), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vendor_qualification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pr_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('purchase_conditions', sa.Text(), nullable=True),
    sa.Column('quality_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('workflow_instance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('validation_snapshot', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PENDING_APPROVAL','APPROVED','PARTIALLY_RECEIVED','CLOSED','CANCELLED','REJECTED')", name=op.f('ck_purchase_order_status')),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_request.id'], name=op.f('fk_purchase_order_pr_id_purchase_request')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_purchase_order_vendor_id_vendor')),
    sa.ForeignKeyConstraint(['vendor_qualification_id'], ['vendor_qualification.id'], name=op.f('fk_purchase_order_vendor_qualification_id_vendor_qualification')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instance.id'], name=op.f('fk_purchase_order_workflow_instance_id_workflow_instance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order')),
    sa.UniqueConstraint('po_no', name=op.f('uq_purchase_order_po_no'))
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('purchase_request_line',
    sa.Column('pr_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('preferred_vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('po_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_request_line_quantity')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_purchase_request_line_material_id_material')),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_request.id'], name=op.f('fk_purchase_request_line_pr_id_purchase_request')),
    sa.ForeignKeyConstraint(['preferred_vendor_id'], ['vendor.id'], name=op.f('fk_purchase_request_line_preferred_vendor_id_vendor')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_purchase_request_line_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_request_line')),
    sa.UniqueConstraint('pr_id', 'line_no', name=op.f('uq_purchase_request_line_pr_id'))
    )
    with op.batch_alter_table('purchase_request_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_request_line_pr_id'), ['pr_id'], unique=False)

    op.create_table('purchase_order_line',
    sa.Column('po_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('specification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vendor_material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pr_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_order_line_quantity')),
    sa.CheckConstraint('rate >= 0', name=op.f('ck_purchase_order_line_rate')),
    sa.CheckConstraint('tax_pct >= 0 AND tax_pct <= 100', name=op.f('ck_purchase_order_line_tax')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_purchase_order_line_material_id_material')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_line_po_id_purchase_order')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], name=op.f('fk_purchase_order_line_specification_id_specification')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_purchase_order_line_unit_id_unit')),
    sa.ForeignKeyConstraint(['vendor_material_id'], ['vendor_material.id'], name=op.f('fk_purchase_order_line_vendor_material_id_vendor_material')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line')),
    sa.UniqueConstraint('po_id', 'line_no', name=op.f('uq_purchase_order_line_po_id'))
    )
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_po_id'), ['po_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_po_id'))

    op.drop_table('purchase_order_line')
    with op.batch_alter_table('purchase_request_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_request_line_pr_id'))

    op.drop_table('purchase_request_line')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_vendor_id'))

    op.drop_table('purchase_order')
    op.drop_table('purchase_request')
    with op.batch_alter_table('vendor_qualification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_qualification_vendor_id'))

    op.drop_table('vendor_qualification')
    with op.batch_alter_table('vendor_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_material_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_material_material_id'))

    op.drop_table('vendor_material')
    # ### end Alembic commands ###
