"""phase4 warehouse

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0004 = ("inventory_transaction", "material_label", "storage_temperature_log")

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_item')),
    sa.UniqueConstraint('code', name=op.f('uq_checklist_item_code'))
    )
    op.create_table('quality_hold',
    sa.Column('hold_no', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=15), nullable=False),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=15), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('ref', sa.String(length=60), nullable=True),
    sa.Column('placed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('placed_at', UTC_DT, nullable=False),
    sa.Column('released_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('released_at', UTC_DT, nullable=True),
    sa.Column('release_reason', sa.String(length=500), nullable=True),
    sa.Column('release_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("entity_type IN ('MATERIAL_BATCH','MFG_BATCH')", name=op.f('ck_quality_hold_entity_type')),
    sa.CheckConstraint("status IN ('OPEN','RELEASED')", name=op.f('ck_quality_hold_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_hold'))
    )
    with op.batch_alter_table('quality_hold', schema=None) as batch_op:
        batch_op.create_index('ix_hold_entity', ['entity_type', 'record_id', 'status'], unique=False)

    op.create_table('storage_temperature_log',
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reading', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recorded_at', UTC_DT, nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('excursion', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_storage_temperature_log_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_temperature_log'))
    )
    with op.batch_alter_table('storage_temperature_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_temperature_log_location_id'), ['location_id'], unique=False)

    op.create_table('material_batch',
    sa.Column('lot_no', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('grn_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('manufacturing_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('vendor_batch_no', sa.String(length=60), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('retest_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('disposition', sa.String(length=15), nullable=False),
    sa.Column('qc_no', sa.String(length=40), nullable=True),
    sa.Column('qa_release_no', sa.String(length=40), nullable=True),
    sa.Column('released_at', UTC_DT, nullable=True),
    sa.Column('release_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('specification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sampling_plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("disposition IN ('QUARANTINE', 'QC_TESTING', 'QC_APPROVED', 'QA_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', 'RETURNED', 'DESTROYED')", name=op.f('ck_material_batch_disposition')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_material_batch_material_id_material')),
    sa.ForeignKeyConstraint(['sampling_plan_id'], ['sampling_plan.id'], name=op.f('fk_material_batch_sampling_plan_id_sampling_plan')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], name=op.f('fk_material_batch_specification_id_specification')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_material_batch_unit_id_unit')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_material_batch_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_batch')),
    sa.UniqueConstraint('lot_no', name=op.f('uq_material_batch_lot_no'))
    )
    with op.batch_alter_table('material_batch', schema=None) as batch_op:
        batch_op.create_index('ix_lot_material_disp', ['material_id', 'disposition'], unique=False)

    op.create_table('destruction_record',
    sa.Column('destruction_no', sa.String(length=30), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('executed_at', UTC_DT, nullable=True),
    sa.Column('ledger_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','APPROVED','REJECTED','EXECUTED')", name=op.f('ck_destruction_record_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_destruction_record_qty')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_destruction_record_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_destruction_record_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destruction_record')),
    sa.UniqueConstraint('destruction_no', name=op.f('uq_destruction_record_destruction_no'))
    )
    op.create_table('inventory_balance',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('qty_reserved', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('qty_on_hand >= 0', name=op.f('ck_inventory_balance_on_hand')),
    sa.CheckConstraint('qty_reserved <= qty_on_hand', name=op.f('ck_inventory_balance_reserved_le_on_hand')),
    sa.CheckConstraint('qty_reserved >= 0', name=op.f('ck_inventory_balance_reserved')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_inventory_balance_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_inventory_balance_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_balance')),
    sa.UniqueConstraint('material_batch_id', 'location_id', name=op.f('uq_inventory_balance_material_batch_id'))
    )
    with op.batch_alter_table('inventory_balance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_balance_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balance_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('inventory_transaction',
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('txn_type', sa.String(length=15), nullable=False),
    sa.Column('from_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('to_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ref_doc_type', sa.String(length=30), nullable=True),
    sa.Column('ref_doc_id', sa.String(length=40), nullable=True),
    sa.Column('reverses_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('txn_ts', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("txn_type IN ('RECEIPT','TRANSFER','SAMPLE','ISSUE','RETURN','REJECT_MOVE','DESTROY','ADJUST_IN','ADJUST_OUT','DISPATCH','OUTPUT')", name=op.f('ck_inventory_transaction_txn_type')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_transaction_qty_positive')),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], name=op.f('fk_inventory_transaction_from_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_inventory_transaction_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], name=op.f('fk_inventory_transaction_to_location_id_location')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_inventory_transaction_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transaction'))
    )
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_invtxn_batch_ts', ['material_batch_id', 'txn_ts'], unique=False)

    op.create_table('material_container',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('container_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['material_batch.id'], name=op.f('fk_material_container_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_container')),
    sa.UniqueConstraint('batch_id', 'container_no', name=op.f('uq_material_container_batch_id'))
    )
    with op.batch_alter_table('material_container', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_container_batch_id'), ['batch_id'], unique=False)

    op.create_table('material_label',
    sa.Column('label_no', sa.String(length=30), nullable=False),
    sa.Column('label_type', sa.String(length=15), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.String(length=40), nullable=True),
    sa.Column('template_version', sa.String(length=10), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('reprint_reason', sa.String(length=300), nullable=True),
    sa.Column('printed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('printed_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_material_label_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_label')),
    sa.UniqueConstraint('label_no', name=op.f('uq_material_label_label_no'))
    )
    with op.batch_alter_table('material_label', schema=None) as batch_op:
        batch_op.create_index('ix_label_batch', ['material_batch_id'], unique=False)

    op.create_table('grn',
    sa.Column('grn_no', sa.String(length=30), nullable=False),
    sa.Column('grn_date', sa.Date(), nullable=False),
    sa.Column('po_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vendor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('invoice_no', sa.String(length=60), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('vehicle_no', sa.String(length=30), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('transport_details', sa.String(length=300), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('received_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checklist_passed', sa.Boolean(), nullable=True),
    sa.Column('quarantine_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('verified_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','VERIFIED','QUARANTINE','REJECTED','CANCELLED')", name=op.f('ck_grn_status')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], name=op.f('fk_grn_po_id_purchase_order')),
    sa.ForeignKeyConstraint(['quarantine_location_id'], ['location.id'], name=op.f('fk_grn_quarantine_location_id_location')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], name=op.f('fk_grn_vendor_id_vendor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grn')),
    sa.UniqueConstraint('grn_no', name=op.f('uq_grn_grn_no'))
    )
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_po_id'), ['po_id'], unique=False)

    op.create_table('grn_checklist',
    sa.Column('grn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('answer', sa.String(length=3), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('exception_ref', sa.String(length=100), nullable=True),
    sa.Column('exception_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("answer IN ('YES','NO','NA')", name=op.f('ck_grn_checklist_answer')),
    sa.ForeignKeyConstraint(['exception_signature_id'], ['e_signature.id'], name=op.f('fk_grn_checklist_exception_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.id'], name=op.f('fk_grn_checklist_grn_id_grn')),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item.id'], name=op.f('fk_grn_checklist_item_id_checklist_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grn_checklist')),
    sa.UniqueConstraint('grn_id', 'item_id', name=op.f('uq_grn_checklist_grn_id'))
    )
    with op.batch_alter_table('grn_checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_checklist_grn_id'), ['grn_id'], unique=False)

    op.create_table('grn_line',
    sa.Column('grn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('po_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vendor_batch_no', sa.String(length=60), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pack_count', sa.Integer(), nullable=False),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('retest_date', sa.Date(), nullable=True),
    sa.Column('coa_received', sa.Boolean(), nullable=False),
    sa.Column('container_condition', sa.String(length=100), nullable=True),
    sa.Column('seal_condition', sa.String(length=100), nullable=True),
    sa.Column('packaging_condition', sa.String(length=100), nullable=True),
    sa.Column('temperature_condition', sa.String(length=100), nullable=True),
    sa.Column('other_documents', sa.String(length=300), nullable=True),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR mfg_date IS NULL OR expiry_date >= mfg_date', name=op.f('ck_grn_line_dates')),
    sa.CheckConstraint('quantity_received > 0', name=op.f('ck_grn_line_qty')),
    sa.ForeignKeyConstraint(['grn_id'], ['grn.id'], name=op.f('fk_grn_line_grn_id_grn')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_grn_line_material_id_material')),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_line.id'], name=op.f('fk_grn_line_po_line_id_purchase_order_line')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_grn_line_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grn_line')),
    sa.UniqueConstraint('grn_id', 'line_no', name=op.f('uq_grn_line_grn_id'))
    )
    with op.batch_alter_table('grn_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_line_grn_id'), ['grn_id'], unique=False)

    # ### end Alembic commands ###

    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0004)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0004)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_line_grn_id'))

    op.drop_table('grn_line')
    with op.batch_alter_table('grn_checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_checklist_grn_id'))

    op.drop_table('grn_checklist')
    with op.batch_alter_table('grn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_po_id'))

    op.drop_table('grn')
    with op.batch_alter_table('material_label', schema=None) as batch_op:
        batch_op.drop_index('ix_label_batch')

    op.drop_table('material_label')
    with op.batch_alter_table('material_container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_container_batch_id'))

    op.drop_table('material_container')
    with op.batch_alter_table('inventory_transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_invtxn_batch_ts')

    op.drop_table('inventory_transaction')
    with op.batch_alter_table('inventory_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_balance_material_batch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balance_location_id'))

    op.drop_table('inventory_balance')
    op.drop_table('destruction_record')
    with op.batch_alter_table('material_batch', schema=None) as batch_op:
        batch_op.drop_index('ix_lot_material_disp')

    op.drop_table('material_batch')
    with op.batch_alter_table('storage_temperature_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_temperature_log_location_id'))

    op.drop_table('storage_temperature_log')
    with op.batch_alter_table('quality_hold', schema=None) as batch_op:
        batch_op.drop_index('ix_hold_entity')

    op.drop_table('quality_hold')
    op.drop_table('checklist_item')
    # ### end Alembic commands ###
