"""phase5 qc

Revision ID: 0005
Revises: 0004
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0005 = ("coa",)

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coa',
    sa.Column('coa_no', sa.String(length=30), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('mfg_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('pdf_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('xlsx_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('conclusion', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('generated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('generated_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_coa_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['pdf_document_id'], ['document.id'], name=op.f('fk_coa_pdf_document_id_document')),
    sa.ForeignKeyConstraint(['xlsx_document_id'], ['document.id'], name=op.f('fk_coa_xlsx_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coa')),
    sa.UniqueConstraint('coa_no', 'version_no', name=op.f('uq_coa_coa_no'))
    )
    with op.batch_alter_table('coa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coa_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('conditional_release',
    sa.Column('cr_no', sa.String(length=30), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity_authorised', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('intended_batch_ref', sa.String(length=60), nullable=False),
    sa.Column('mfg_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('justification', sa.String(length=1000), nullable=False),
    sa.Column('risk_assessment_ref', sa.String(length=60), nullable=False),
    sa.Column('identity_confirmed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decided_at', UTC_DT, nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','APPROVED','REJECTED','CLOSED','EXPIRED')", name=op.f('ck_conditional_release_status')),
    sa.CheckConstraint('quantity_authorised > 0', name=op.f('ck_conditional_release_qty')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_conditional_release_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_conditional_release_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conditional_release')),
    sa.UniqueConstraint('cr_no', name=op.f('uq_conditional_release_cr_no'))
    )
    with op.batch_alter_table('conditional_release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditional_release_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('sample',
    sa.Column('sample_no', sa.String(length=30), nullable=False),
    sa.Column('sample_type', sa.String(length=15), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('mfg_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('specification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sampling_plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity_sampled', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('containers_sampled', sa.Integer(), nullable=False),
    sa.Column('sampling_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sampled_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sampled_at', UTC_DT, nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('disposal_approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('disposal_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('disposed_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("sample_type IN ('RM_SAMPLE', 'PM_SAMPLE', 'IN_PROCESS', 'SFG', 'FG', 'STABILITY', 'RETENTION', 'VENDOR', 'INVESTIGATION')", name=op.f('ck_sample_sample_type')),
    sa.CheckConstraint("status IN ('CREATED','TESTING','COMPLETED','RETAINED','DISPOSED')", name=op.f('ck_sample_status')),
    sa.CheckConstraint('quantity_sampled > 0', name=op.f('ck_sample_qty')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_sample_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['sampling_location_id'], ['location.id'], name=op.f('fk_sample_sampling_location_id_location')),
    sa.ForeignKeyConstraint(['sampling_plan_id'], ['sampling_plan.id'], name=op.f('fk_sample_sampling_plan_id_sampling_plan')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], name=op.f('fk_sample_specification_id_specification')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_sample_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sample')),
    sa.UniqueConstraint('sample_no', name=op.f('uq_sample_sample_no'))
    )
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_material_batch_id'), ['material_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_mfg_batch_id'), ['mfg_batch_id'], unique=False)

    op.create_table('qc_test',
    sa.Column('sample_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('spec_parameter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('stp_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('analyst_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('calibration_status', sa.String(length=20), nullable=True),
    sa.Column('calibration_override_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('retest_of_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('started_at', UTC_DT, nullable=True),
    sa.Column('completed_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('ASSIGNED','STARTED','SUBMITTED','INVALIDATED')", name=op.f('ck_qc_test_status')),
    sa.ForeignKeyConstraint(['calibration_override_signature_id'], ['e_signature.id'], name=op.f('fk_qc_test_calibration_override_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_qc_test_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], name=op.f('fk_qc_test_sample_id_sample')),
    sa.ForeignKeyConstraint(['spec_parameter_id'], ['specification_parameter.id'], name=op.f('fk_qc_test_spec_parameter_id_specification_parameter')),
    sa.ForeignKeyConstraint(['stp_id'], ['stp.id'], name=op.f('fk_qc_test_stp_id_stp')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_test'))
    )
    with op.batch_alter_table('qc_test', schema=None) as batch_op:
        batch_op.create_index('ix_qctest_sample', ['sample_id'], unique=False)

    op.create_table('qc_result',
    sa.Column('test_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('spec_type', sa.String(length=10), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rounded_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('lsl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('decimal_places', sa.Integer(), nullable=True),
    sa.Column('acceptance_criteria', sa.String(length=300), nullable=True),
    sa.Column('pass_fail', sa.String(length=4), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('entered_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entered_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("pass_fail IN ('PASS','FAIL','NA')", name=op.f('ck_qc_result_pass_fail')),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED')", name=op.f('ck_qc_result_status')),
    sa.ForeignKeyConstraint(['test_id'], ['qc_test.id'], name=op.f('fk_qc_result_test_id_qc_test')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_result')),
    sa.UniqueConstraint('test_id', name=op.f('uq_qc_result_test_id'))
    )
    op.create_table('oos_investigation',
    sa.Column('oos_no', sa.String(length=30), nullable=False),
    sa.Column('qc_result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qc_test_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sample_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('phase1_findings', sa.Text(), nullable=True),
    sa.Column('phase2_findings', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('capa_ref', sa.String(length=60), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('decided_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('hold_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('raised_at', UTC_DT, nullable=False),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('RAISED','PHASE1','PHASE2','DECIDED','CLOSED')", name=op.f('ck_oos_investigation_status')),
    sa.ForeignKeyConstraint(['decision_signature_id'], ['e_signature.id'], name=op.f('fk_oos_investigation_decision_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_oos_investigation_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['qc_result_id'], ['qc_result.id'], name=op.f('fk_oos_investigation_qc_result_id_qc_result')),
    sa.ForeignKeyConstraint(['qc_test_id'], ['qc_test.id'], name=op.f('fk_oos_investigation_qc_test_id_qc_test')),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], name=op.f('fk_oos_investigation_sample_id_sample')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oos_investigation')),
    sa.UniqueConstraint('oos_no', name=op.f('uq_oos_investigation_oos_no'))
    )
    op.create_table('oot_event',
    sa.Column('oot_no', sa.String(length=30), nullable=False),
    sa.Column('qc_result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('rule', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_oot_event_material_id_material')),
    sa.ForeignKeyConstraint(['qc_result_id'], ['qc_result.id'], name=op.f('fk_oot_event_qc_result_id_qc_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oot_event')),
    sa.UniqueConstraint('oot_no', name=op.f('uq_oot_event_oot_no'))
    )
    op.create_table('qc_result_amendment',
    sa.Column('result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('original_value', sa.String(length=300), nullable=True),
    sa.Column('new_value', sa.String(length=300), nullable=False),
    sa.Column('new_pass_fail', sa.String(length=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decided_at', UTC_DT, nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','APPROVED','REJECTED')", name=op.f('ck_qc_result_amendment_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_qc_result_amendment_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['result_id'], ['qc_result.id'], name=op.f('fk_qc_result_amendment_result_id_qc_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_result_amendment'))
    )
    with op.batch_alter_table('qc_result_amendment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_result_amendment_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###

    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0005)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0005)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qc_result_amendment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_result_amendment_result_id'))

    op.drop_table('qc_result_amendment')
    op.drop_table('oot_event')
    op.drop_table('oos_investigation')
    op.drop_table('qc_result')
    with op.batch_alter_table('qc_test', schema=None) as batch_op:
        batch_op.drop_index('ix_qctest_sample')

    op.drop_table('qc_test')
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_mfg_batch_id'))
        batch_op.drop_index(batch_op.f('ix_sample_material_batch_id'))

    op.drop_table('sample')
    with op.batch_alter_table('conditional_release', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditional_release_material_batch_id'))

    op.drop_table('conditional_release')
    with op.batch_alter_table('coa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coa_material_batch_id'))

    op.drop_table('coa')
    # ### end Alembic commands ###
