"""phase6 manufacturing

Revision ID: 0006
Revises: 0005
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0006 = ("material_issue", "ipc_result", "immunisation_record")

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('animal_tag', sa.String(length=30), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('health_notes', sa.String(length=500), nullable=True),
    sa.Column('min_bleed_interval_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','QUARANTINED','RETIRED','DECEASED')", name=op.f('ck_animal_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal')),
    sa.UniqueConstraint('animal_tag', name=op.f('uq_animal_animal_tag'))
    )
    op.create_table('bleed_record',
    sa.Column('bleed_no', sa.String(length=30), nullable=False),
    sa.Column('animal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bled_on', sa.Date(), nullable=False),
    sa.Column('volume_l', sa.Numeric(precision=9, scale=3), nullable=False),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('pool_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('volume_l > 0', name=op.f('ck_bleed_record_vol')),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_bleed_record_animal_id_animal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bleed_record')),
    sa.UniqueConstraint('bleed_no', name=op.f('uq_bleed_record_bleed_no'))
    )
    with op.batch_alter_table('bleed_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bleed_record_animal_id'), ['animal_id'], unique=False)

    op.create_table('immunisation_record',
    sa.Column('animal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('antigen', sa.String(length=100), nullable=False),
    sa.Column('dose', sa.String(length=60), nullable=True),
    sa.Column('administered_on', sa.Date(), nullable=False),
    sa.Column('administered_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name=op.f('fk_immunisation_record_animal_id_animal')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_immunisation_record'))
    )
    with op.batch_alter_table('immunisation_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunisation_record_animal_id'), ['animal_id'], unique=False)

    op.create_table('bom_header',
    sa.Column('bom_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('product_material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('batch_size', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('expected_yield_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('yield_min_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('yield_max_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_bom_header_status')),
    sa.CheckConstraint('batch_size > 0', name=op.f('ck_bom_header_batch_size')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_bom_header_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['product_material_id'], ['material.id'], name=op.f('fk_bom_header_product_material_id_material')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['bom_header.id'], name=op.f('fk_bom_header_supersedes_id_bom_header')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_bom_header_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_header')),
    sa.UniqueConstraint('bom_no', 'version_no', name=op.f('uq_bom_header_bom_no'))
    )
    with op.batch_alter_table('bom_header', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_header_product_material_id'), ['product_material_id'], unique=False)

    op.create_table('bom_line',
    sa.Column('bom_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('process_loss_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('overage_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sampling_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reconcile', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('overage_pct >= 0 AND process_loss_pct >= 0', name=op.f('ck_bom_line_pct')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_bom_line_quantity')),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_header.id'], name=op.f('fk_bom_line_bom_id_bom_header')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_bom_line_material_id_material')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_bom_line_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_line')),
    sa.UniqueConstraint('bom_id', 'line_no', name=op.f('uq_bom_line_bom_id'))
    )
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bom_line_bom_id'), ['bom_id'], unique=False)

    op.create_table('manufacturing_batch',
    sa.Column('batch_no', sa.String(length=40), nullable=False),
    sa.Column('batch_type', sa.String(length=3), nullable=False),
    sa.Column('product_material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bom_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('number_override_reason', sa.String(length=300), nullable=True),
    sa.Column('uses_conditional_release', sa.Boolean(), nullable=False),
    sa.Column('line_clearance_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('output_lot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('start_at', UTC_DT, nullable=True),
    sa.Column('end_at', UTC_DT, nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("batch_type IN ('SFG','FG')", name=op.f('ck_manufacturing_batch_batch_type')),
    sa.CheckConstraint("status IN ('CREATED', 'MATERIAL_ISSUED', 'IN_PROCESS', 'PRODUCTION_COMPLETE', 'RECONCILED', 'QC_QA', 'RELEASED', 'REJECTED', 'CANCELLED')", name=op.f('ck_manufacturing_batch_status')),
    sa.CheckConstraint('planned_qty > 0', name=op.f('ck_manufacturing_batch_planned')),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_header.id'], name=op.f('fk_manufacturing_batch_bom_id_bom_header')),
    sa.ForeignKeyConstraint(['line_clearance_signature_id'], ['e_signature.id'], name=op.f('fk_manufacturing_batch_line_clearance_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['product_material_id'], ['material.id'], name=op.f('fk_manufacturing_batch_product_material_id_material')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_manufacturing_batch_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manufacturing_batch')),
    sa.UniqueConstraint('batch_no', name=op.f('uq_manufacturing_batch_batch_no'))
    )
    op.create_table('mbr_step',
    sa.Column('bom_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=True),
    sa.Column('instruction', sa.String(length=1000), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('requires_value', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['bom_header.id'], name=op.f('fk_mbr_step_bom_id_bom_header')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mbr_step')),
    sa.UniqueConstraint('bom_id', 'step_no', name=op.f('uq_mbr_step_bom_id'))
    )
    with op.batch_alter_table('mbr_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mbr_step_bom_id'), ['bom_id'], unique=False)

    op.create_table('batch_equipment_use',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('used_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', UTC_DT, nullable=False),
    sa.Column('ended_at', UTC_DT, nullable=True),
    sa.Column('calibration_status', sa.String(length=20), nullable=True),
    sa.Column('cleaning_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_batch_equipment_use_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_batch_equipment_use_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_equipment_use'))
    )
    with op.batch_alter_table('batch_equipment_use', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_equipment_use_batch_id'), ['batch_id'], unique=False)

    op.create_table('batch_material',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bom_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reconcile', sa.Boolean(), nullable=False),
    sa.Column('issued_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('returned_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('consumed_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sample_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('waste_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('required_qty >= 0', name=op.f('ck_batch_material_required')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_batch_material_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['bom_line_id'], ['bom_line.id'], name=op.f('fk_batch_material_bom_line_id_bom_line')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_batch_material_material_id_material')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_batch_material_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_material')),
    sa.UniqueConstraint('batch_id', 'bom_line_id', name=op.f('uq_batch_material_batch_id'))
    )
    with op.batch_alter_table('batch_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_material_batch_id'), ['batch_id'], unique=False)

    op.create_table('batch_reconciliation',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('within_tolerance', sa.Boolean(), nullable=False),
    sa.Column('yield_ok', sa.Boolean(), nullable=False),
    sa.Column('tolerance_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('deviation_ref', sa.String(length=60), nullable=True),
    sa.Column('justification', sa.String(length=500), nullable=True),
    sa.Column('production_approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('production_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('qa_approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('qa_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('CALCULATED','PRODUCTION_APPROVED','APPROVED')", name=op.f('ck_batch_reconciliation_status')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_batch_reconciliation_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['production_signature_id'], ['e_signature.id'], name=op.f('fk_batch_reconciliation_production_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['qa_signature_id'], ['e_signature.id'], name=op.f('fk_batch_reconciliation_qa_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_reconciliation')),
    sa.UniqueConstraint('batch_id', name=op.f('uq_batch_reconciliation_batch_id'))
    )
    op.create_table('batch_step_execution',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(length=1000), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('recorded_value', sa.String(length=200), nullable=True),
    sa.Column('performed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('performed_at', UTC_DT, nullable=True),
    sa.Column('verified_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('verified_at', UTC_DT, nullable=True),
    sa.Column('verify_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_batch_step_execution_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['verify_signature_id'], ['e_signature.id'], name=op.f('fk_batch_step_execution_verify_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_step_execution')),
    sa.UniqueConstraint('batch_id', 'step_no', name=op.f('uq_batch_step_execution_batch_id'))
    )
    with op.batch_alter_table('batch_step_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_step_execution_batch_id'), ['batch_id'], unique=False)

    op.create_table('ipc_result',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('lsl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pass_fail', sa.String(length=4), nullable=False),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('analyst_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('recorded_at', UTC_DT, nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("pass_fail IN ('PASS','FAIL','NA')", name=op.f('ck_ipc_result_pass_fail')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_ipc_result_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_ipc_result_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ipc_result'))
    )
    with op.batch_alter_table('ipc_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipc_result_batch_id'), ['batch_id'], unique=False)

    op.create_table('material_issue_indent',
    sa.Column('indent_no', sa.String(length=30), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_material_issue_indent_batch_id_manufacturing_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_issue_indent')),
    sa.UniqueConstraint('batch_id', name=op.f('uq_material_issue_indent_batch_id')),
    sa.UniqueConstraint('indent_no', name=op.f('uq_material_issue_indent_indent_no'))
    )
    op.create_table('plasma_pool',
    sa.Column('pool_no', sa.String(length=30), nullable=False),
    sa.Column('total_volume_l', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_plasma_pool_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plasma_pool')),
    sa.UniqueConstraint('pool_no', name=op.f('uq_plasma_pool_pool_no'))
    )
    op.create_table('material_issue',
    sa.Column('issue_no', sa.String(length=30), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('inventory_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('conditional_release_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('fefo_override_reason', sa.String(length=300), nullable=True),
    sa.Column('is_additional', sa.Boolean(), nullable=False),
    sa.Column('issued_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('issued_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_material_issue_qty')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_material_issue_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['batch_material_id'], ['batch_material.id'], name=op.f('fk_material_issue_batch_material_id_batch_material')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_material_issue_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_material_issue_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_issue')),
    sa.UniqueConstraint('issue_no', name=op.f('uq_material_issue_issue_no'))
    )
    with op.batch_alter_table('material_issue', schema=None) as batch_op:
        batch_op.create_index('ix_issue_lot', ['material_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_issue_batch_id'), ['batch_id'], unique=False)

    op.create_table('material_return',
    sa.Column('return_no', sa.String(length=30), nullable=False),
    sa.Column('issue_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('issued_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('used_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('returned_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('damaged_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('accepted_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('accepted_at', UTC_DT, nullable=True),
    sa.Column('ledger_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('decision_comment', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','ACCEPTED','REJECTED')", name=op.f('ck_material_return_status')),
    sa.CheckConstraint('returned_qty > 0', name=op.f('ck_material_return_qty')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_material_return_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['batch_material_id'], ['batch_material.id'], name=op.f('fk_material_return_batch_material_id_batch_material')),
    sa.ForeignKeyConstraint(['issue_id'], ['material_issue.id'], name=op.f('fk_material_return_issue_id_material_issue')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_material_return_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_material_return_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_return')),
    sa.UniqueConstraint('return_no', name=op.f('uq_material_return_return_no'))
    )
    # ### end Alembic commands ###
    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0006)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0006)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_return')
    with op.batch_alter_table('material_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_issue_batch_id'))
        batch_op.drop_index('ix_issue_lot')

    op.drop_table('material_issue')
    op.drop_table('plasma_pool')
    op.drop_table('material_issue_indent')
    with op.batch_alter_table('ipc_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipc_result_batch_id'))

    op.drop_table('ipc_result')
    with op.batch_alter_table('batch_step_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_step_execution_batch_id'))

    op.drop_table('batch_step_execution')
    op.drop_table('batch_reconciliation')
    with op.batch_alter_table('batch_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_material_batch_id'))

    op.drop_table('batch_material')
    with op.batch_alter_table('batch_equipment_use', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_equipment_use_batch_id'))

    op.drop_table('batch_equipment_use')
    with op.batch_alter_table('mbr_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbr_step_bom_id'))

    op.drop_table('mbr_step')
    op.drop_table('manufacturing_batch')
    with op.batch_alter_table('bom_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_line_bom_id'))

    op.drop_table('bom_line')
    with op.batch_alter_table('bom_header', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bom_header_product_material_id'))

    op.drop_table('bom_header')
    with op.batch_alter_table('immunisation_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immunisation_record_animal_id'))

    op.drop_table('immunisation_record')
    with op.batch_alter_table('bleed_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bleed_record_animal_id'))

    op.drop_table('bleed_record')
    op.drop_table('animal')
    # ### end Alembic commands ###
