"""phase7 dispatch

Revision ID: 0007
Revises: 0006
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('dispatch_no', sa.String(length=30), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('invoice_no', sa.String(length=40), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('vehicle_no', sa.String(length=30), nullable=True),
    sa.Column('lr_no', sa.String(length=40), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('validation_snapshot', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', UTC_DT, nullable=True),
    sa.Column('dispatched_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('dispatched_at', UTC_DT, nullable=True),
    sa.Column('delivered_at', UTC_DT, nullable=True),
    sa.Column('delivery_remarks', sa.String(length=300), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'VALIDATED', 'APPROVED', 'DISPATCHED', 'DELIVERED', 'CANCELLED')", name=op.f('ck_dispatch_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_dispatch_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_dispatch_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch')),
    sa.UniqueConstraint('dispatch_no', name=op.f('uq_dispatch_dispatch_no'))
    )
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_customer_id'), ['customer_id'], unique=False)

    op.create_table('dispatch_line',
    sa.Column('dispatch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=False),
    sa.Column('coa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('ledger_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_dispatch_line_qty')),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch.id'], name=op.f('fk_dispatch_line_dispatch_id_dispatch')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_dispatch_line_location_id_location')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_dispatch_line_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], name=op.f('fk_dispatch_line_unit_id_unit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_line')),
    sa.UniqueConstraint('dispatch_id', 'line_no', name=op.f('uq_dispatch_line_dispatch_id'))
    )
    with op.batch_alter_table('dispatch_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_line_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_line_material_batch_id'), ['material_batch_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_remaining_shelf_life_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('min_remaining_shelf_life_days')

    with op.batch_alter_table('dispatch_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_line_material_batch_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_line_dispatch_id'))

    op.drop_table('dispatch_line')
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_customer_id'))

    op.drop_table('dispatch')
    # ### end Alembic commands ###
