"""phase8 quality system

Revision ID: 0008
Revises: 0007
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0008 = ("sop_acknowledgement",)

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capa',
    sa.Column('capa_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capa_type', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=15), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=True),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('effectiveness_due', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effectiveness_result', sa.String(length=15), nullable=True),
    sa.Column('effectiveness_comment', sa.String(length=500), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('close_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'IN_PROGRESS', 'EFFECTIVENESS_CHECK', 'CLOSED', 'CANCELLED')", name=op.f('ck_capa_status')),
    sa.ForeignKeyConstraint(['close_signature_id'], ['e_signature.id'], name=op.f('fk_capa_close_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa')),
    sa.UniqueConstraint('capa_no', name=op.f('uq_capa_capa_no'))
    )
    op.create_table('change_control',
    sa.Column('cc_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('change_type', sa.String(length=15), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('regulatory_impact', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', UTC_DT, nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=True),
    sa.Column('implementation_notes', sa.Text(), nullable=True),
    sa.Column('effectiveness_notes', sa.Text(), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('close_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ASSESSMENT', 'APPROVAL', 'IMPLEMENTATION', 'EFFECTIVENESS', 'CLOSED', 'REJECTED', 'CANCELLED')", name=op.f('ck_change_control_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_change_control_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['close_signature_id'], ['e_signature.id'], name=op.f('fk_change_control_close_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_control')),
    sa.UniqueConstraint('cc_no', name=op.f('uq_change_control_cc_no'))
    )
    op.create_table('deviation',
    sa.Column('dev_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=15), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('blocks_release', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('raised_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('containment', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('no_capa_justification', sa.String(length=500), nullable=True),
    sa.Column('capa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('close_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('close_comment', sa.String(length=500), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("severity IN ('MINOR','MAJOR','CRITICAL')", name=op.f('ck_deviation_severity')),
    sa.CheckConstraint("status IN ('OPEN', 'INVESTIGATION', 'CAPA_PROPOSED', 'QA_REVIEW', 'CLOSED', 'CANCELLED')", name=op.f('ck_deviation_status')),
    sa.ForeignKeyConstraint(['close_signature_id'], ['e_signature.id'], name=op.f('fk_deviation_close_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deviation')),
    sa.UniqueConstraint('dev_no', name=op.f('uq_deviation_dev_no'))
    )
    op.create_table('risk_assessment',
    sa.Column('ra_no', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_no', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', UTC_DT, nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','APPROVED','OBSOLETE')", name=op.f('ck_risk_assessment_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_risk_assessment_approved_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessment')),
    sa.UniqueConstraint('ra_no', name=op.f('uq_risk_assessment_ra_no'))
    )
    op.create_table('sop',
    sa.Column('sop_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('review_period_months', sa.Integer(), nullable=False),
    sa.Column('review_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_sop_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_sop_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name=op.f('fk_sop_department_id_department')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_sop_document_id_document')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['sop.id'], name=op.f('fk_sop_supersedes_id_sop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sop')),
    sa.UniqueConstraint('sop_no', 'version_no', name=op.f('uq_sop_sop_no'))
    )
    op.create_table('capa_action',
    sa.Column('capa_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('completed_at', UTC_DT, nullable=True),
    sa.Column('completion_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capa_id'], ['capa.id'], name=op.f('fk_capa_action_capa_id_capa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_action'))
    )
    with op.batch_alter_table('capa_action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capa_action_capa_id'), ['capa_id'], unique=False)

    op.create_table('change_control_link',
    sa.Column('cc_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cc_id'], ['change_control.id'], name=op.f('fk_change_control_link_cc_id_change_control')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_control_link')),
    sa.UniqueConstraint('cc_id', 'entity', 'record_id', name=op.f('uq_change_control_link_cc_id'))
    )
    with op.batch_alter_table('change_control_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_control_link_cc_id'), ['cc_id'], unique=False)

    op.create_table('risk_item',
    sa.Column('ra_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('function_step', sa.String(length=200), nullable=False),
    sa.Column('failure_mode', sa.String(length=300), nullable=False),
    sa.Column('effect', sa.String(length=300), nullable=True),
    sa.Column('cause', sa.String(length=300), nullable=True),
    sa.Column('controls', sa.String(length=300), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('detection', sa.Integer(), nullable=False),
    sa.Column('rpn', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('mitigation', sa.String(length=500), nullable=True),
    sa.Column('residual_severity', sa.Integer(), nullable=True),
    sa.Column('residual_occurrence', sa.Integer(), nullable=True),
    sa.Column('residual_detection', sa.Integer(), nullable=True),
    sa.Column('residual_rpn', sa.Integer(), nullable=True),
    sa.Column('residual_level', sa.String(length=8), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('severity BETWEEN 1 AND 10 AND occurrence BETWEEN 1 AND 10 AND detection BETWEEN 1 AND 10', name=op.f('ck_risk_item_scores')),
    sa.ForeignKeyConstraint(['ra_id'], ['risk_assessment.id'], name=op.f('fk_risk_item_ra_id_risk_assessment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_item')),
    sa.UniqueConstraint('ra_id', 'seq', name=op.f('uq_risk_item_ra_id'))
    )
    with op.batch_alter_table('risk_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_item_ra_id'), ['ra_id'], unique=False)

    op.create_table('sop_acknowledgement',
    sa.Column('sop_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('acknowledged_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sop.id'], name=op.f('fk_sop_acknowledgement_sop_id_sop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sop_acknowledgement')),
    sa.UniqueConstraint('sop_id', 'user_id', name=op.f('uq_sop_acknowledgement_sop_id'))
    )
    with op.batch_alter_table('sop_acknowledgement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sop_acknowledgement_sop_id'), ['sop_id'], unique=False)

    op.create_table('complaint',
    sa.Column('complaint_no', sa.String(length=30), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('dispatch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('investigation', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('deviation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('hold_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('close_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("severity IN ('MINOR','MAJOR','CRITICAL')", name=op.f('ck_complaint_severity')),
    sa.CheckConstraint("status IN ('RECEIVED','INVESTIGATION','CLOSED','CANCELLED')", name=op.f('ck_complaint_status')),
    sa.ForeignKeyConstraint(['close_signature_id'], ['e_signature.id'], name=op.f('fk_complaint_close_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_complaint_customer_id_customer')),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch.id'], name=op.f('fk_complaint_dispatch_id_dispatch')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_complaint_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint')),
    sa.UniqueConstraint('complaint_no', name=op.f('uq_complaint_complaint_no'))
    )
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('recall',
    sa.Column('recall_no', sa.String(length=30), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('recall_class', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('complaint_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('initiated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('initiated_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('hold_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closure_summary', sa.String(length=1000), nullable=True),
    sa.Column('closed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('closed_at', UTC_DT, nullable=True),
    sa.Column('close_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("recall_class IN ('I','II','III')", name=op.f('ck_recall_class')),
    sa.CheckConstraint("status IN ('INITIATED','IN_PROGRESS','CLOSED')", name=op.f('ck_recall_status')),
    sa.ForeignKeyConstraint(['close_signature_id'], ['e_signature.id'], name=op.f('fk_recall_close_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['initiated_signature_id'], ['e_signature.id'], name=op.f('fk_recall_initiated_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_recall_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recall')),
    sa.UniqueConstraint('recall_no', name=op.f('uq_recall_recall_no'))
    )
    with op.batch_alter_table('recall', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recall_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('recall_line',
    sa.Column('recall_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dispatch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantity_dispatched', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('notified_at', UTC_DT, nullable=True),
    sa.Column('response', sa.String(length=300), nullable=True),
    sa.Column('quantity_returned', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('quantity_consumed_or_unrecoverable', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_recall_line_customer_id_customer')),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch.id'], name=op.f('fk_recall_line_dispatch_id_dispatch')),
    sa.ForeignKeyConstraint(['recall_id'], ['recall.id'], name=op.f('fk_recall_line_recall_id_recall')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recall_line')),
    sa.UniqueConstraint('recall_id', 'dispatch_id', name=op.f('uq_recall_line_recall_id'))
    )
    with op.batch_alter_table('recall_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recall_line_recall_id'), ['recall_id'], unique=False)

    # ### end Alembic commands ###
    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0008)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0008)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recall_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recall_line_recall_id'))

    op.drop_table('recall_line')
    with op.batch_alter_table('recall', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recall_material_batch_id'))

    op.drop_table('recall')
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_material_batch_id'))

    op.drop_table('complaint')
    with op.batch_alter_table('sop_acknowledgement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sop_acknowledgement_sop_id'))

    op.drop_table('sop_acknowledgement')
    with op.batch_alter_table('risk_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_item_ra_id'))

    op.drop_table('risk_item')
    with op.batch_alter_table('change_control_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_control_link_cc_id'))

    op.drop_table('change_control_link')
    with op.batch_alter_table('capa_action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capa_action_capa_id'))

    op.drop_table('capa_action')
    op.drop_table('sop')
    op.drop_table('risk_assessment')
    op.drop_table('deviation')
    op.drop_table('change_control')
    op.drop_table('capa')
    # ### end Alembic commands ###
