"""phase9 reporting

Revision ID: 0009
Revises: 0008
"""
from alembic import op
import sqlalchemy as sa


from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0009 = ("report_run", "archive_batch", "backup_record")

revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_record',
    sa.Column('backup_type', sa.String(length=15), nullable=False),
    sa.Column('performed_at', UTC_DT, nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('size_mb', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('audit_chain_verified', sa.Boolean(), nullable=True),
    sa.Column('rto_minutes', sa.Integer(), nullable=True),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('recorded_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("backup_type IN ('FULL','DIFFERENTIAL','LOG','DOCUMENTS','RESTORE_TEST')", name=op.f('ck_backup_record_type')),
    sa.CheckConstraint("result IN ('SUCCESS','FAILED')", name=op.f('ck_backup_record_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_record'))
    )
    op.create_table('report_run',
    sa.Column('copy_no', sa.String(length=30), nullable=False),
    sa.Column('report_code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('output_format', sa.String(length=8), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('run_at', UTC_DT, nullable=False),
    sa.Column('ref_entity', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_run')),
    sa.UniqueConstraint('copy_no', name=op.f('uq_report_run_copy_no'))
    )
    with op.batch_alter_table('report_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_run_report_code'), ['report_code'], unique=False)

    op.create_table('retention_policy',
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('legal_hold_reason', sa.String(length=500), nullable=True),
    sa.Column('basis', sa.String(length=300), nullable=True),
    sa.Column('last_archived_cutoff', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('retention_years >= 1', name=op.f('ck_retention_policy_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policy')),
    sa.UniqueConstraint('record_type', name=op.f('uq_retention_policy_record_type'))
    )
    op.create_table('archive_batch',
    sa.Column('archive_no', sa.String(length=30), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('to_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_archive_batch_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_batch')),
    sa.UniqueConstraint('archive_no', name=op.f('uq_archive_batch_archive_no'))
    )
    with op.batch_alter_table('archive_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_batch_record_type'), ['record_type'], unique=False)

    # ### end Alembic commands ###
    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0009)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0009)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archive_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_batch_record_type'))

    op.drop_table('archive_batch')
    op.drop_table('retention_policy')
    with op.batch_alter_table('report_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_run_report_code'))

    op.drop_table('report_run')
    op.drop_table('backup_record')
    # ### end Alembic commands ###
