"""phase11 em stability costing

Revision ID: 0010
Revises: 0009
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

UTC_DT = sa.DateTime().with_variant(mssql.DATETIME2(6), "mssql")
_AO_0010 = ("em_result_amendment", "stability_result", "lot_cost")


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_cost',
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('std_unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('std_unit_cost >= 0', name=op.f('ck_standard_cost_std')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_standard_cost_material_id_material')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standard_cost')),
    sa.UniqueConstraint('material_id', name=op.f('uq_standard_cost_material_id'))
    )
    op.create_table('em_location',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("grade IN ('A', 'B', 'C', 'D', 'NC')", name=op.f('ck_em_location_grade')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_em_location_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_location')),
    sa.UniqueConstraint('code', name=op.f('uq_em_location_code'))
    )
    op.create_table('cost_rate_card',
    sa.Column('card_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('labour_rate_per_hour', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('machine_rate_per_hour', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_cost_rate_card_status')),
    sa.CheckConstraint('labour_rate_per_hour >= 0 AND machine_rate_per_hour >= 0 AND overhead_pct >= 0', name=op.f('ck_cost_rate_card_rates')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_cost_rate_card_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['cost_rate_card.id'], name=op.f('fk_cost_rate_card_supersedes_id_cost_rate_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_rate_card')),
    sa.UniqueConstraint('card_no', 'version_no', name=op.f('uq_cost_rate_card_card_no'))
    )
    op.create_table('em_limit_set',
    sa.Column('limitset_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('basis', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_em_limit_set_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_em_limit_set_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['em_limit_set.id'], name=op.f('fk_em_limit_set_supersedes_id_em_limit_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_limit_set')),
    sa.UniqueConstraint('limitset_no', 'version_no', name=op.f('uq_em_limit_set_limitset_no'))
    )
    op.create_table('em_plan',
    sa.Column('em_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sample_type', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('frequency_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('frequency_days > 0', name=op.f('ck_em_plan_freq')),
    sa.ForeignKeyConstraint(['em_location_id'], ['em_location.id'], name=op.f('fk_em_plan_em_location_id_em_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_plan')),
    sa.UniqueConstraint('em_location_id', 'sample_type', 'state', name=op.f('uq_em_plan_em_location_id'))
    )
    with op.batch_alter_table('em_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_em_plan_em_location_id'), ['em_location_id'], unique=False)

    op.create_table('em_limit',
    sa.Column('limit_set_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('sample_type', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('alert_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('action_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('alert_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('action_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("grade IN ('A', 'B', 'C', 'D', 'NC')", name=op.f('ck_em_limit_grade')),
    sa.CheckConstraint("state IN ('AT_REST', 'OPERATIONAL')", name=op.f('ck_em_limit_state')),
    sa.ForeignKeyConstraint(['limit_set_id'], ['em_limit_set.id'], name=op.f('fk_em_limit_limit_set_id_em_limit_set')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_limit')),
    sa.UniqueConstraint('limit_set_id', 'grade', 'sample_type', 'state', name=op.f('uq_em_limit_key')),
    sa.UniqueConstraint('limit_set_id', 'seq', name=op.f('uq_em_limit_seq'))
    )
    with op.batch_alter_table('em_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_em_limit_limit_set_id'), ['limit_set_id'], unique=False)

    op.create_table('stability_protocol',
    sa.Column('protocol_no', sa.String(length=40), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('specification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('container_closure', sa.String(length=200), nullable=True),
    sa.Column('proposed_shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('pull_window_days', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('effective_from', UTC_DT, nullable=True),
    sa.Column('effective_to', UTC_DT, nullable=True),
    sa.Column('change_reason', sa.String(length=1000), nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','UNDER_REVIEW','APPROVED','SUPERSEDED')", name=op.f('ck_stability_protocol_status')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_stability_protocol_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name=op.f('fk_stability_protocol_material_id_material')),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], name=op.f('fk_stability_protocol_specification_id_specification')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['stability_protocol.id'], name=op.f('fk_stability_protocol_supersedes_id_stability_protocol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_protocol')),
    sa.UniqueConstraint('protocol_no', 'version_no', name=op.f('uq_stability_protocol_protocol_no'))
    )
    with op.batch_alter_table('stability_protocol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_protocol_material_id'), ['material_id'], unique=False)

    op.create_table('batch_cost',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('rate_card_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('labour_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('machine_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('machine_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('output_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('standard_unit_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('variance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lines_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('calculated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('approved_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', UTC_DT, nullable=True),
    sa.Column('approved_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','APPROVED')", name=op.f('ck_batch_cost_status')),
    sa.CheckConstraint('labour_hours >= 0 AND machine_hours >= 0', name=op.f('ck_batch_cost_hours')),
    sa.ForeignKeyConstraint(['approved_signature_id'], ['e_signature.id'], name=op.f('fk_batch_cost_approved_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['batch_id'], ['manufacturing_batch.id'], name=op.f('fk_batch_cost_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['rate_card_id'], ['cost_rate_card.id'], name=op.f('fk_batch_cost_rate_card_id_cost_rate_card')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_cost')),
    sa.UniqueConstraint('batch_id', name=op.f('uq_batch_cost_batch_id'))
    )
    op.create_table('em_sample',
    sa.Column('sample_no', sa.String(length=30), nullable=False),
    sa.Column('em_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('plan_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sample_type', sa.String(length=15), nullable=False),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('sample_point', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sampled_at', UTC_DT, nullable=False),
    sa.Column('sampled_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('limit_set_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('alert_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('action_high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('alert_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('action_low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('result_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('result_unit', sa.String(length=20), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.Column('entered_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entered_at', UTC_DT, nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', UTC_DT, nullable=True),
    sa.Column('review_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('deviation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('WITHIN','ALERT','ACTION')", name=op.f('ck_em_sample_outcome')),
    sa.CheckConstraint("sample_type IN ('VIABLE_AIR', 'SETTLE_PLATE', 'CONTACT_PLATE', 'GLOVE_PRINT', 'NONVIABLE_05', 'NONVIABLE_5', 'DIFF_PRESSURE', 'TEMPERATURE', 'HUMIDITY')", name=op.f('ck_em_sample_sample_type')),
    sa.CheckConstraint("status IN ('SAMPLED', 'RESULT_ENTERED', 'REVIEWED', 'CANCELLED')", name=op.f('ck_em_sample_status')),
    sa.ForeignKeyConstraint(['em_location_id'], ['em_location.id'], name=op.f('fk_em_sample_em_location_id_em_location')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_em_sample_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['limit_set_id'], ['em_limit_set.id'], name=op.f('fk_em_sample_limit_set_id_em_limit_set')),
    sa.ForeignKeyConstraint(['manufacturing_batch_id'], ['manufacturing_batch.id'], name=op.f('fk_em_sample_manufacturing_batch_id_manufacturing_batch')),
    sa.ForeignKeyConstraint(['plan_id'], ['em_plan.id'], name=op.f('fk_em_sample_plan_id_em_plan')),
    sa.ForeignKeyConstraint(['review_signature_id'], ['e_signature.id'], name=op.f('fk_em_sample_review_signature_id_e_signature')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_sample')),
    sa.UniqueConstraint('sample_no', name=op.f('uq_em_sample_sample_no'))
    )
    with op.batch_alter_table('em_sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_em_sample_em_location_id'), ['em_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_em_sample_manufacturing_batch_id'), ['manufacturing_batch_id'], unique=False)

    op.create_table('lot_cost',
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('basis', sa.String(length=12), nullable=False),
    sa.Column('po_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('batch_cost_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('recorded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('recorded_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("basis IN ('PO_RATE', 'BATCH_COST', 'MANUAL')", name=op.f('ck_lot_cost_basis')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_lot_cost_unit_cost')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_lot_cost_material_batch_id_material_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_cost'))
    )
    with op.batch_alter_table('lot_cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_cost_material_batch_id'), ['material_batch_id'], unique=False)

    op.create_table('stability_condition',
    sa.Column('protocol_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('condition_type', sa.String(length=15), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('temperature_tol_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rh_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('rh_tol_pct', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('chamber_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("condition_type IN ('LONG_TERM', 'INTERMEDIATE', 'ACCELERATED', 'STRESS', 'REFRIGERATED', 'FROZEN')", name=op.f('ck_stability_condition_ctype')),
    sa.ForeignKeyConstraint(['chamber_location_id'], ['location.id'], name=op.f('fk_stability_condition_chamber_location_id_location')),
    sa.ForeignKeyConstraint(['protocol_id'], ['stability_protocol.id'], name=op.f('fk_stability_condition_protocol_id_stability_protocol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_condition')),
    sa.UniqueConstraint('protocol_id', 'seq', name=op.f('uq_stability_condition_protocol_id'))
    )
    with op.batch_alter_table('stability_condition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_condition_protocol_id'), ['protocol_id'], unique=False)

    op.create_table('stability_study',
    sa.Column('study_no', sa.String(length=30), nullable=False),
    sa.Column('protocol_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('material_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('units_per_pull', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source_location_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', UTC_DT, nullable=True),
    sa.Column('placed_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ledger_txn_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('completed_at', UTC_DT, nullable=True),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('concluded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('concluded_at', UTC_DT, nullable=True),
    sa.Column('conclusion_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('terminate_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CONCLUDED', 'TERMINATED')", name=op.f('ck_stability_study_status')),
    sa.CheckConstraint('units_per_pull > 0', name=op.f('ck_stability_study_units')),
    sa.ForeignKeyConstraint(['conclusion_signature_id'], ['e_signature.id'], name=op.f('fk_stability_study_conclusion_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['material_batch_id'], ['material_batch.id'], name=op.f('fk_stability_study_material_batch_id_material_batch')),
    sa.ForeignKeyConstraint(['protocol_id'], ['stability_protocol.id'], name=op.f('fk_stability_study_protocol_id_stability_protocol')),
    sa.ForeignKeyConstraint(['source_location_id'], ['location.id'], name=op.f('fk_stability_study_source_location_id_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_study')),
    sa.UniqueConstraint('study_no', name=op.f('uq_stability_study_study_no'))
    )
    with op.batch_alter_table('stability_study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_study_material_batch_id'), ['material_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_study_protocol_id'), ['protocol_id'], unique=False)

    op.create_table('stability_timepoint',
    sa.Column('protocol_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('month >= 0', name=op.f('ck_stability_timepoint_month')),
    sa.ForeignKeyConstraint(['protocol_id'], ['stability_protocol.id'], name=op.f('fk_stability_timepoint_protocol_id_stability_protocol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_timepoint')),
    sa.UniqueConstraint('protocol_id', 'month', name=op.f('uq_stability_timepoint_month')),
    sa.UniqueConstraint('protocol_id', 'seq', name=op.f('uq_stability_timepoint_seq'))
    )
    with op.batch_alter_table('stability_timepoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_timepoint_protocol_id'), ['protocol_id'], unique=False)

    op.create_table('em_isolate',
    sa.Column('sample_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('organism', sa.String(length=150), nullable=False),
    sa.Column('gram_stain', sa.String(length=20), nullable=True),
    sa.Column('cfu_count', sa.Integer(), nullable=False),
    sa.Column('identification_method', sa.String(length=100), nullable=True),
    sa.Column('identified_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('cfu_count >= 0', name=op.f('ck_em_isolate_cfu')),
    sa.ForeignKeyConstraint(['sample_id'], ['em_sample.id'], name=op.f('fk_em_isolate_sample_id_em_sample')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_isolate'))
    )
    with op.batch_alter_table('em_isolate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_em_isolate_sample_id'), ['sample_id'], unique=False)

    op.create_table('em_result_amendment',
    sa.Column('sample_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('old_outcome', sa.String(length=8), nullable=True),
    sa.Column('new_outcome', sa.String(length=8), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amended_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['em_sample.id'], name=op.f('fk_em_result_amendment_sample_id_em_sample')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_em_result_amendment'))
    )
    with op.batch_alter_table('em_result_amendment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_em_result_amendment_sample_id'), ['sample_id'], unique=False)

    op.create_table('stability_pull',
    sa.Column('study_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('condition_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('timepoint_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pulled_at', UTC_DT, nullable=True),
    sa.Column('pulled_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actual_qty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tested_at', UTC_DT, nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', UTC_DT, nullable=True),
    sa.Column('review_signature_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('deviation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('oos_deviation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', UTC_DT, nullable=False),
    sa.Column('created_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_at', UTC_DT, nullable=True),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('SCHEDULED', 'PULLED', 'TESTED', 'REVIEWED', 'MISSED', 'SKIPPED')", name=op.f('ck_stability_pull_status')),
    sa.ForeignKeyConstraint(['condition_id'], ['stability_condition.id'], name=op.f('fk_stability_pull_condition_id_stability_condition')),
    sa.ForeignKeyConstraint(['review_signature_id'], ['e_signature.id'], name=op.f('fk_stability_pull_review_signature_id_e_signature')),
    sa.ForeignKeyConstraint(['study_id'], ['stability_study.id'], name=op.f('fk_stability_pull_study_id_stability_study')),
    sa.ForeignKeyConstraint(['timepoint_id'], ['stability_timepoint.id'], name=op.f('fk_stability_pull_timepoint_id_stability_timepoint')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_pull')),
    sa.UniqueConstraint('study_id', 'condition_id', 'timepoint_id', name=op.f('uq_stability_pull_study_id'))
    )
    with op.batch_alter_table('stability_pull', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_pull_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stability_pull_study_id'), ['study_id'], unique=False)

    op.create_table('stability_result',
    sa.Column('pull_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('parameter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rounded_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('lsl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('usl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('pass_fail', sa.String(length=4), nullable=False),
    sa.Column('equipment_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('supersedes_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('correction_reason', sa.String(length=500), nullable=True),
    sa.Column('deviation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entered_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('entered_at', UTC_DT, nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("pass_fail IN ('PASS','FAIL')", name=op.f('ck_stability_result_pf')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_stability_result_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['parameter_id'], ['specification_parameter.id'], name=op.f('fk_stability_result_parameter_id_specification_parameter')),
    sa.ForeignKeyConstraint(['pull_id'], ['stability_pull.id'], name=op.f('fk_stability_result_pull_id_stability_pull')),
    sa.ForeignKeyConstraint(['supersedes_id'], ['stability_result.id'], name=op.f('fk_stability_result_supersedes_id_stability_result')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stability_result'))
    )
    with op.batch_alter_table('stability_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stability_result_pull_id'), ['pull_id'], unique=False)

    # ### end Alembic commands ###
    from app.audit.immutability import install_triggers
    install_triggers(op.get_bind(), _AO_0010)


def downgrade() -> None:
    from app.audit.immutability import drop_triggers
    drop_triggers(op.get_bind(), _AO_0010)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stability_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_result_pull_id'))

    op.drop_table('stability_result')
    with op.batch_alter_table('stability_pull', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_pull_study_id'))
        batch_op.drop_index(batch_op.f('ix_stability_pull_due_date'))

    op.drop_table('stability_pull')
    with op.batch_alter_table('em_result_amendment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_em_result_amendment_sample_id'))

    op.drop_table('em_result_amendment')
    with op.batch_alter_table('em_isolate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_em_isolate_sample_id'))

    op.drop_table('em_isolate')
    with op.batch_alter_table('stability_timepoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_timepoint_protocol_id'))

    op.drop_table('stability_timepoint')
    with op.batch_alter_table('stability_study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_study_protocol_id'))
        batch_op.drop_index(batch_op.f('ix_stability_study_material_batch_id'))

    op.drop_table('stability_study')
    with op.batch_alter_table('stability_condition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_condition_protocol_id'))

    op.drop_table('stability_condition')
    with op.batch_alter_table('lot_cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_cost_material_batch_id'))

    op.drop_table('lot_cost')
    with op.batch_alter_table('em_sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_em_sample_manufacturing_batch_id'))
        batch_op.drop_index(batch_op.f('ix_em_sample_em_location_id'))

    op.drop_table('em_sample')
    op.drop_table('batch_cost')
    with op.batch_alter_table('stability_protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stability_protocol_material_id'))

    op.drop_table('stability_protocol')
    with op.batch_alter_table('em_limit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_em_limit_limit_set_id'))

    op.drop_table('em_limit')
    with op.batch_alter_table('em_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_em_plan_em_location_id'))

    op.drop_table('em_plan')
    op.drop_table('em_limit_set')
    op.drop_table('cost_rate_card')
    op.drop_table('em_location')
    op.drop_table('standard_cost')
    # ### end Alembic commands ###
