"""Single source of truth for the User Requirements Specification (URS) and the Requirements Traceability Matrix (RTM).

Each requirement: (id, area, text, gmp_impact, business_rules, [tests]).  Tests are `path::function` node ids relative to the repository root.
`scripts/gen_validation_docs.py` renders docs/validation/urs.md and rtm.md from this list and FAILS if a referenced test does not exist,
so the matrix cannot silently rot. GMP impact: C = critical (direct product/patient/data-integrity effect), M = major, N = minor."""

W = "tests/workflows/"
S = "tests/security/"
I = "tests/integration/"
U = "tests/unit/"
V = "tests/validation/test_critical_15.py::"

REQS = [
    # ------------------------------------------------------------------ identity, security, audit, signatures
    ("URS-IAM-01", "Security", "Unique user IDs with local or directory (LDAP/AD) authentication; failed attempts are indistinguishable between unknown user and bad password.", "C", "BR-SEC-002",
     [S + "test_auth.py::test_login_logout_and_me", S + "test_auth.py::test_unknown_user_and_bad_password_give_same_generic_error", S + "test_ldap_provider.py::test_ldap_user_logs_in_with_directory_password", S + "test_ldap_provider.py::test_ldap_disabled_fails_closed"]),
    ("URS-IAM-02", "Security", "Account lockout after repeated failures, idle session timeout, forced password change, password policy and history.", "C", "BR-SEC-002",
     [S + "test_auth.py::test_lockout_after_threshold_and_events_logged", S + "test_auth.py::test_idle_timeout_expires_session", S + "test_auth.py::test_must_change_password_blocks_other_endpoints", S + "test_auth.py::test_password_policy_and_history", S + "test_auth.py::test_login_rate_limit"]),
    ("URS-IAM-03", "Security", "Role-based access control with least privilege; every endpoint authenticated; permission checked per role (generated matrix).", "C", "BR-SEC-001",
     [S + "test_access_matrix.py::test_every_route_requires_authentication", S + "test_access_matrix.py::test_generated_role_by_route_permission_matrix", S + "test_rbac.py::test_unauthorised_user_gets_403_and_event_logged", I + "test_master_data.py::test_role_access_matrix_phase2"]),
    ("URS-IAM-04", "Security", "Segregation of duties: administrators hold no GMP authority; users cannot change their own roles; creators cannot approve own records.", "C", "BR-SOD-001",
     [S + "test_access_matrix.py::test_admin_roles_hold_no_gmp_approval_authority", S + "test_rbac.py::test_admin_cannot_hold_gmp_approval_role_sod09", S + "test_rbac.py::test_cannot_change_own_roles_sod10", V + "test_crit_11_creator_cannot_approve_own_transaction"]),
    ("URS-IAM-05", "Security", "Session/CSRF protection, secure headers, no credential exposure, injection and upload hardening.", "C", "BR-SEC-001",
     [S + "test_auth.py::test_csrf_required_on_state_change", S + "test_hardening.py::test_sql_injection_payloads_in_every_search_and_filter_are_inert", S + "test_hardening.py::test_status_and_system_columns_cannot_be_mass_assigned",
      S + "test_hardening.py::test_upload_validation_rejects_disguised_oversized_and_traversal_files", S + "test_hardening.py::test_no_credential_material_in_any_api_response", S + "test_hardening.py::test_session_cookie_flags_and_logout_invalidates_session",
      S + "test_hardening.py::test_state_changing_requests_without_csrf_token_are_refused_everywhere", S + "test_auth.py::test_unhandled_error_hides_internals"]),
    ("URS-AUD-01", "Audit trail", "Secure, time-stamped, field-level audit trail (who/what/when/old/new/reason) written in the same transaction as the change.", "C", "BR-AUD-002",
     [I + "test_audit_trail.py::test_field_level_audit_with_old_new_user_reason", I + "test_audit_trail.py::test_audit_written_in_same_transaction_rollback_removes_both", I + "test_audit_trail.py::test_master_update_without_reason_is_rejected_and_rolled_back"]),
    ("URS-AUD-02", "Audit trail", "The audit trail cannot be modified or deleted (ORM, database, API); tampering is detectable through the hash chain.", "C", "BR-AUD-001",
     [V + "test_crit_09_audit_trail_cannot_be_modified_or_deleted", I + "test_audit_trail.py::test_audit_rows_cannot_be_modified_with_raw_sql_db_trigger", I + "test_audit_trail.py::test_hash_chain_verifies_and_detects_tampering", I + "test_audit_trail.py::test_hash_chain_detects_removed_tail",
      I + "test_audit_trail.py::test_normal_roles_have_no_audit_write_endpoints", W + "test_state_and_approval.py::test_ledger_style_append_only_tables_refuse_update"]),
    ("URS-SIG-01", "E-signature", "Electronic signatures require re-authentication, carry printed name/meaning/time, are bound to the record content hash and cannot be edited.", "C", "BR-SIG-001",
     [V + "test_crit_10_electronic_signature_required_and_bound_to_the_record", W + "test_state_and_approval.py::test_signature_failure_counts_toward_lockout", W + "test_state_and_approval.py::test_signer_without_permission_refused", W + "test_state_and_approval.py::test_training_gate_blocks_signing_until_trained"]),
    ("URS-SIG-02", "E-signature", "Controlled status engine: only legal transitions, permission-gated, history recorded; status columns cannot be written from payloads.", "C", "BR-SEC-001",
     [W + "test_state_and_approval.py::test_legal_transition_records_history_and_audit", W + "test_state_and_approval.py::test_illegal_transition_blocked", W + "test_state_and_approval.py::test_direct_status_assignment_refused_BR_SEC_001", S + "test_rbac.py::test_status_not_writable_via_api_payload"]),
    ("URS-SIG-03", "Workflow", "Configurable approval chains with SoD, QA-approved definitions, rejection with reason and versioned definitions.", "M", "WF-001",
     [W + "test_state_and_approval.py::test_two_step_chain_with_signatures_and_sod", W + "test_state_and_approval.py::test_initiator_cannot_approve_own_submission", W + "test_state_and_approval.py::test_definition_needs_qa_signature_and_sod_author_neq_approver", W + "test_state_and_approval.py::test_approved_definition_is_versioned_not_overwritten"]),
    ("URS-SYS-01", "System", "Duplicate-free configurable document numbering (concurrency-safe, no reuse).", "M", "",
     [U + "test_numbering_and_passwords.py::test_no_duplicates_under_concurrency", U + "test_numbering_and_passwords.py::test_rollback_does_not_burn_committed_numbers", U + "test_numbering_and_passwords.py::test_yearly_reset", I + "test_company_documents.py::test_numbering_config_change_audited_and_validated"]),
    ("URS-SYS-02", "System", "Database schema deploys by versioned migrations (up/down) with append-only protections installed on all supported dialects.", "C", "BR-AUD-001",
     [I + "test_migrations.py::test_alembic_upgrade_matches_models_and_installs_triggers", I + "test_migrations.py::test_ddl_generated_for_all_dialects"]),
    # ------------------------------------------------------------------ master data
    ("URS-MD-01", "Master data", "Vendor master with approval, documents (hash-verified, write-once) and reviewed expiry.", "M", "BR-DOC-001",
     [I + "test_master_data.py::test_vendor_lifecycle_sod_and_signature", I + "test_master_data.py::test_vendor_documents_review_and_integrity", S + "test_hardening.py::test_upload_validation_rejects_disguised_oversized_and_traversal_files"]),
    ("URS-MD-02", "Master data", "Material master (types, categories, units, shelf life, FEFO mode) with approval and lifecycle.", "M", "BR-PO-004",
     [I + "test_master_data.py::test_material_validation_and_lifecycle", I + "test_master_data.py::test_material_author_cannot_approve_sod14"]),
    ("URS-MD-03", "Master data", "Versioned STP, specification and sampling plan: draft-only editing, QA e-signature approval, supersede, point-in-time lookup.", "C", "BR-HIS-001",
     [W + "test_versioned_masters.py::test_approved_version_is_immutable_and_new_version_supersedes", W + "test_versioned_masters.py::test_specification_flow_historical_link_and_parameter_rules", W + "test_versioned_masters.py::test_stp_requires_procedure_then_approve_with_signature_and_sod",
      W + "test_versioned_masters.py::test_author_cannot_approve_own_stp_sod16", W + "test_versioned_masters.py::test_sampling_plan_rules_and_versions", V + "test_crit_12_historical_gmp_records_are_never_overwritten"]),
    ("URS-MD-04", "Master data", "Locations with hierarchy, storage compatibility and capacity; equipment with qualification and calibration status.", "M", "BR-LOC-001/002",
     [I + "test_locations_equipment.py::test_hierarchy_rules_and_path", I + "test_locations_equipment.py::test_storage_compatibility_checks", I + "test_locations_equipment.py::test_incompatible_category_rule", I + "test_locations_equipment.py::test_calibration_gate_for_testing"]),
    ("URS-MD-05", "Master data", "Controlled Excel import with staging, validation and execution only of unchanged validated data.", "M", "",
     [I + "test_import.py::test_full_import_flow_vendor", I + "test_import.py::test_validation_errors_block_submission_and_report", I + "test_import.py::test_import_rows_cannot_be_executed_if_data_changed_since_validation", I + "test_import.py::test_upload_rejects_wrong_format_and_missing_columns"]),
    # ------------------------------------------------------------------ purchase
    ("URS-PUR-01", "Purchase", "Vendor qualification (versioned, signed) with expiry job and alerts; requalification keeps history.", "C", "BR-VQ-001..004",
     [W + "test_purchase_requests.py::test_vendor_qualification_readiness_and_sod", W + "test_purchase_requests.py::test_qualification_content_locked_after_submission_and_author_sod", W + "test_purchase_rules.py::test_expiry_job_persists_status_notifies_and_is_idempotent",
      W + "test_purchase_rules.py::test_requalification_restores_purchasing_and_keeps_history", W + "test_purchase_rules.py::test_suspended_and_disqualified_vendor_blocked_and_adverse_actions_are_signed"]),
    ("URS-PUR-02", "Purchase", "PO is blocked for an expired vendor qualification (critical rule 1).", "C", "BR-PO-001",
     [W + "test_purchase_rules.py::test_crit_01_expired_vendor_cannot_create_po"]),
    ("URS-PUR-03", "Purchase", "PO is blocked for an unapproved / suspended / inactive vendor (critical rule 2).", "C", "BR-PO-002",
     [W + "test_purchase_rules.py::test_crit_02_unapproved_vendor_cannot_purchase", W + "test_purchase_rules.py::test_inactive_vendor_master_blocks_po"]),
    ("URS-PUR-04", "Purchase", "PO is blocked for a vendor not approved for the material; mapping is versioned and QA-approved (critical rule 3).", "C", "BR-PO-003, BR-VM-001",
     [W + "test_purchase_rules.py::test_crit_03_wrong_vendor_material_combination", W + "test_purchase_rules.py::test_mapping_versioning_and_sod"]),
    ("URS-PUR-05", "Purchase", "Further PO gates (spec, documents, active material, units, values) evaluated at create, submit and approve with a full violation report.", "M", "BR-PO-004..010",
     [W + "test_purchase_rules.py::test_other_po_gate_rules_spec_material_documents", W + "test_purchase_rules.py::test_gate_reports_all_violations_and_warnings", W + "test_purchase_rules.py::test_po_material_must_be_active_and_unit_checked", W + "test_purchase_rules.py::test_baseline_po_is_created_with_pins_and_totals"]),
    ("URS-PUR-06", "Purchase", "PR and PO approval chains with e-signature, SoD, rejection/cancellation and locked content after submission.", "M", "BR-PO-007, BR-PR-001",
     [W + "test_purchase_rules.py::test_po_approval_chain_signature_sod_and_gate_recheck", W + "test_purchase_rules.py::test_sod_creator_cannot_approve_own_po", W + "test_purchase_rules.py::test_po_rejection_and_cancellation", W + "test_purchase_rules.py::test_po_audit_trail_and_status_history",
      W + "test_purchase_requests.py::test_pr_full_flow_department_then_purchase_review_then_po", W + "test_purchase_requests.py::test_pr_rejection_and_cancellation"]),
    # ------------------------------------------------------------------ warehouse
    ("URS-WH-01", "Warehouse", "GRN against an approved PO with configurable checklist; critical failure blocks verification unless QA grants a signed exception; second-person verification.", "C", "BR-GRN-001..005",
     [W + "test_warehouse.py::test_grn_requires_approved_po_and_blocks_over_delivery_and_bad_dates", W + "test_warehouse.py::test_critical_checklist_failure_blocks_receipt_until_qa_exception", W + "test_warehouse.py::test_second_person_verification_and_incomplete_checklist",
      W + "test_warehouse.py::test_qa_can_reject_receipt", W + "test_warehouse.py::test_partial_receipts_and_po_status"]),
    ("URS-WH-02", "Warehouse", "Verified receipt creates a quarantine lot with containers and a ledger receipt; labels (Code128/QR) are controlled and audited.", "C", "BR-QRN-001, BR-LBL-001..003",
     [W + "test_warehouse.py::test_receipt_creates_quarantine_lot_containers_ledger_and_closes_po", W + "test_warehouse.py::test_quarantine_location_required_and_vendor_expiry_at_receipt_places_hold", W + "test_warehouse.py::test_labels_are_controlled_audited_and_limited"]),
    ("URS-WH-03", "Warehouse", "Quarantine material cannot be issued (critical rule 4).", "C", "BR-ISS-001",
     [W + "test_warehouse.py::test_crit_04_quarantine_material_cannot_be_issued", W + "test_manufacturing.py::test_issue_gates_quarantine_rejected_expired_held"]),
    ("URS-WH-04", "Warehouse", "Rejected material (critical rule 5) and expired / retest-expired material (critical rule 7) cannot be issued.", "C", "BR-ISS-002, BR-ISS-004",
     [W + "test_warehouse.py::test_crit_05_rejected_and_crit_07_expired_material_cannot_be_issued", W + "test_manufacturing.py::test_issue_gates_quarantine_rejected_expired_held"]),
    ("URS-WH-05", "Warehouse", "Quality hold blocks issue, use and dispatch; only QA places/releases with e-signature (critical rule 8).", "C", "BR-HOLD-001..004",
     [V + "test_crit_08_quality_hold_blocks_issue_use_and_dispatch", W + "test_warehouse.py::test_quality_hold_blocks_use_and_release_needs_qa_head_signature"]),
    ("URS-WH-06", "Warehouse", "Authoritative append-only inventory ledger; balances reconcile; no negative stock; concurrency-safe (critical rule 13).", "C", "BR-INV-001..003",
     [V + "test_crit_13_every_stock_movement_creates_an_inventory_transaction", W + "test_warehouse.py::test_ledger_matches_balances_and_detects_drift", W + "test_warehouse.py::test_ledger_is_append_only_and_lot_is_immutable", W + "test_warehouse.py::test_concurrent_issues_cannot_overdraw_stock"]),
    ("URS-WH-07", "Warehouse", "FEFO/FIFO pick order, put-away/transfer rules for quarantine/approved/rejected stock, expiry alerts, temperature excursions and controlled destruction.", "M", "BR-INV-005/006, BR-TMP-001",
     [W + "test_warehouse.py::test_fefo_pick_order_and_exclusions", W + "test_warehouse.py::test_transfer_rules_for_quarantine_approved_and_rejected_stock", W + "test_warehouse.py::test_expiry_job_and_alerts", W + "test_warehouse.py::test_temperature_excursion_places_holds_on_stored_lots",
      W + "test_warehouse.py::test_destruction_requires_rejected_stock_and_qa_signature", W + "test_manufacturing.py::test_fefo_deviation_needs_reason"]),
    # ------------------------------------------------------------------ QC
    ("URS-QC-01", "QC / LIMS", "Sampling per plan with ledger sample transaction; tests follow the specification version pinned at sampling.", "C", "BR-SMP-001/002, BR-QC-001",
     [W + "test_qc.py::test_sampling_plan_ledger_and_state", W + "test_qc.py::test_tests_follow_pinned_specification_even_after_spec_revision"]),
    ("URS-QC-02", "QC / LIMS", "Results evaluated server-side (rounding, inclusive limits), immutable once submitted; amendments retain originals with approval.", "C", "BR-QC-004/005",
     [W + "test_qc.py::test_result_entry_evaluation_rounding_and_immutability", W + "test_qc.py::test_assigned_test_is_restricted_to_its_analyst_and_boundaries_are_inclusive", W + "test_qc.py::test_result_amendment_workflow_retains_original"]),
    ("URS-QC-03", "QC / LIMS", "Instrument calibration gate with controlled QA override.", "C", "BR-QC-002",
     [W + "test_qc.py::test_calibration_gate_blocks_testing_and_override_is_controlled"]),
    ("URS-QC-04", "QC / LIMS", "OOS investigation workflow with automatic hold, retest, QA decision; OOT detection never changes disposition.", "C", "BR-QC-007, BR-STAT-002",
     [W + "test_qc.py::test_failing_result_raises_oos_and_places_hold", W + "test_qc.py::test_oos_invalidated_allows_retest_and_release_path", W + "test_qc.py::test_oos_confirmed_rejects_lot", W + "test_qc.py::test_oot_alert_limit_flags_but_never_changes_disposition"]),
    ("URS-QC-05", "QC / LIMS", "Release chain QC → QA with distinct signers, readiness checks, QC/QA numbers, CoA issued only after release.", "C", "BR-REL-001..004, BR-QC-006",
     [W + "test_qc.py::test_full_release_chain_to_approved_coa_and_issuable_lot", W + "test_qc.py::test_release_chain_enforces_order_roles_and_separation_of_duties", W + "test_qc.py::test_one_person_cannot_hold_two_release_steps_sod03",
      W + "test_qc.py::test_analyst_who_tested_cannot_review_even_with_reviewer_role", W + "test_qc.py::test_release_rejection_makes_lot_unissuable_crit_05", W + "test_qc.py::test_release_blocked_by_missing_coa_hold_or_open_oos", W + "test_qc.py::test_coa_requires_release_and_reissue_creates_new_version"]),
    ("URS-QC-06", "QC / LIMS", "Conditional release is a quantity- and batch-bounded QA exception; a batch using it cannot be released until the material is finally approved.", "C", "BR-CRL-001..004",
     [W + "test_qc.py::test_conditional_release_is_a_controlled_exception", W + "test_manufacturing.py::test_conditional_material_blocks_batch_release"]),
    ("URS-QC-07", "QC / LIMS", "Statistics (Cp/Cpk/Pp/Ppk with explicit status codes, I-MR limits, Nelson rules), trending and sample retention.", "M", "BR-STAT-001",
     [W + "test_qc.py::test_stats_reference_values_and_status_codes", W + "test_qc.py::test_nelson_rules_and_control_limits", W + "test_qc.py::test_trend_endpoint_groups_and_capability_status", W + "test_qc.py::test_sample_retention_and_disposal"]),
    # ------------------------------------------------------------------ manufacturing
    ("URS-MFG-01", "Manufacturing", "Versioned BOM with MBR steps, QA e-signature approval; only an approved in-force BOM can start a batch and is pinned to it.", "C", "BR-BOM-001/002",
     [W + "test_manufacturing.py::test_bom_lifecycle_and_immutability", W + "test_manufacturing.py::test_bom_validation", W + "test_manufacturing.py::test_batch_requires_approved_bom_and_scales_requirements"]),
    ("URS-MFG-02", "Manufacturing", "Unique batch numbers with controlled override; cancelled numbers are never reused.", "C", "BR-BAT-001/002",
     [W + "test_manufacturing.py::test_duplicate_batch_number_prevented_and_override_controlled"]),
    ("URS-MFG-03", "Manufacturing", "Material issue only of released, unexpired, unheld, BOM-correct lots; FEFO deviation needs a reason; every issue links lot and batch (critical rule 14).", "C", "BR-ISS-001..007, BR-TRC-001",
     [V + "test_crit_14_issued_material_is_always_linked_to_lot_and_production_batch", W + "test_manufacturing.py::test_issue_links_lot_and_batch_and_posts_ledger", W + "test_manufacturing.py::test_issue_is_audited_and_traceable"]),
    ("URS-MFG-04", "Manufacturing", "Returns require independent acceptance and re-enter stock through the ledger.", "M", "BR-RET-001",
     [W + "test_manufacturing.py::test_return_workflow_and_sod"]),
    ("URS-MFG-05", "Manufacturing", "Process execution: line clearance signature, ordered steps, second-person verification, equipment gate, IPC failure holds the batch.", "C", "BR-MFG-001..004",
     [W + "test_manufacturing.py::test_process_execution_controls", W + "test_manufacturing.py::test_ipc_failure_places_batch_on_hold_and_blocks_completion", W + "test_manufacturing.py::test_equipment_gate"]),
    ("URS-MFG-06", "Manufacturing", "Reconciliation discrepancy is highlighted, raises a deviation and blocks progress until QA accepts it (critical rule 15).", "C", "BR-REC-001",
     [V + "test_crit_15_reconciliation_discrepancy_is_highlighted_and_blocks_progress", W + "test_manufacturing.py::test_reconciliation_within_tolerance", W + "test_manufacturing.py::test_reconciliation_discrepancy_blocks_until_qa_deviation"]),
    ("URS-MFG-07", "Manufacturing", "Output is booked into quarantine and released through the QC/QA chain; antisera donor → bleed → pool genealogy.", "M", "BR-ANM-001..003",
     [W + "test_manufacturing.py::test_output_lot_flows_into_qc_and_release_marks_batch", W + "test_manufacturing.py::test_antisera_animal_bleed_pool_genealogy"]),
    # ------------------------------------------------------------------ dispatch & traceability
    ("URS-DSP-01", "Dispatch", "Unreleased FG cannot be dispatched (critical rule 6); dispatch validated at validate/approve/dispatch with customer and shelf-life rules.", "C", "BR-DSP-001..006",
     [W + "test_dispatch.py::test_crit_06_unreleased_fg_cannot_be_dispatched", W + "test_dispatch.py::test_hold_expiry_customer_and_oos_blocks", W + "test_dispatch.py::test_rm_and_wrong_type_cannot_be_dispatched"]),
    ("URS-DSP-02", "Dispatch", "Dispatch flow with stock reservation, QA e-signature approval (creator ≠ approver), ledger transaction and CoA link.", "C", "BR-DSP-003/006",
     [W + "test_dispatch.py::test_released_fg_full_dispatch_flow", W + "test_dispatch.py::test_sod_creator_cannot_approve", W + "test_dispatch.py::test_hold_after_validation_blocks_approval_and_dispatch_and_cancel_releases_stock", W + "test_dispatch.py::test_dispatch_is_audited_and_permissioned"]),
    ("URS-TRC-01", "Traceability", "Complete forward and backward genealogy (vendor ↔ PO ↔ GRN ↔ lot ↔ batch ↔ FG ↔ dispatch ↔ customer; animal ↔ pool), global search and QR resolution.", "C", "BR-TRC-001",
     [W + "test_dispatch.py::test_traceability_backward_and_forward_are_complete", W + "test_dispatch.py::test_trace_excludes_undispatched_and_antisera_genealogy", W + "test_dispatch.py::test_global_search_respects_permissions_and_qr_resolve"]),
    # ------------------------------------------------------------------ quality system
    ("URS-QS-01", "Quality system", "Deviation workflow; open deviations block release/dispatch; independent QA closure; automatic deviations from IPC, temperature and reconciliation.", "C", "BR-DEV-001..003",
     [W + "test_quality_system.py::test_open_deviation_blocks_release_until_closed_with_independent_qa_signature", W + "test_quality_system.py::test_deviation_raiser_cannot_close_and_non_blocking_flag", W + "test_quality_system.py::test_temperature_excursion_raises_deviation_and_hold",
      W + "test_quality_system.py::test_ipc_failure_raises_deviation_on_batch", W + "test_quality_system.py::test_reconciliation_deviation_blocks_output_lot_release"]),
    ("URS-QS-02", "Quality system", "CAPA with actions, effectiveness check, ineffective loop, independent closure.", "M", "BR-CAPA-001/002",
     [W + "test_quality_system.py::test_capa_lifecycle_effectiveness_and_sod", W + "test_quality_system.py::test_capa_creator_cannot_close_own_capa"]),
    ("URS-QS-03", "Quality system", "Change control linked to versioned masters; approval required for new master versions when enabled; SoD.", "C", "BR-CC-001..003, BR-BOM-002, BR-VM-001",
     [W + "test_quality_system.py::test_change_control_gates_new_master_versions", W + "test_quality_system.py::test_change_control_requester_cannot_approve_and_rejection"]),
    ("URS-QS-04", "Quality system", "FMEA risk assessment with RPN, mitigation/residual risk and signed approval.", "M", "BR-RSK-001",
     [W + "test_quality_system.py::test_fmea_rpn_levels_and_approval_rules"]),
    ("URS-QS-05", "Quality system", "SOP control: versions, hashed document, effective dates, periodic review and read-and-understood acknowledgement.", "M", "BR-SOP-001/002",
     [W + "test_quality_system.py::test_sop_versioning_acknowledgement_and_review_due"]),
    ("URS-QS-06", "Quality system", "Complaints hold critical lots; recall derives affected customers from the dispatch ledger, reconciles returns and requires signed closure.", "C", "BR-CMP-001, BR-RCL-001..004",
     [W + "test_quality_system.py::test_critical_complaint_holds_lot_and_needs_closed_deviation", W + "test_quality_system.py::test_recall_derives_affected_customers_and_reconciles_returns", W + "test_quality_system.py::test_quality_endpoints_are_permissioned_and_listed"]),
    # ------------------------------------------------------------------ reports, retention, backup
    ("URS-RPT-01", "Reports", "Permissioned reports (37) in JSON/XLSX/CSV/PDF with parameter validation and no field leakage.", "M", "",
     [W + "test_reports.py::test_catalogue_size_and_every_report_runs_with_data", W + "test_reports.py::test_report_permissions_params_and_no_field_leak", I + "test_master_data.py::test_exports_have_report_header_and_are_audited"]),
    ("URS-RPT-02", "Reports", "Controlled copies: numbered, hash-logged (append-only), verifiable printouts; controlled business PDFs.", "C", "BR-DOC-001",
     [W + "test_reports.py::test_exports_are_controlled_copies_with_hash_verification", W + "test_reports.py::test_controlled_business_documents_pdf"]),
    ("URS-RPT-03", "Reports", "Role dashboards and report performance on large ledgers.", "N", "",
     [W + "test_reports.py::test_dashboards_are_role_gated_and_populated", W + "test_reports.py::test_report_performance_with_large_ledger", I + "test_company_documents.py::test_dashboard_cards"]),
    ("URS-DI-01", "Data integrity", "Retention policies (extend-only), legal hold, non-destructive hashed archive packages; records never deleted by the application.", "C", "BR-RET-001/002",
     [W + "test_reports.py::test_retention_policies_archive_and_legal_hold", I + "test_audit_trail.py::test_physical_delete_of_audited_record_refused"]),
    ("URS-DI-02", "Data integrity", "Backup and restore evidence with alerts for stale backups / missing restore tests.", "M", "",
     [W + "test_reports.py::test_backup_status_and_restore_evidence"]),
]
